export interface TacticsMap { width: number; height: number; terrain: Uint8Array; resources: Uint16Array; }
export interface GridPoint { x: number; y: number; }
export const FLOW_FIELD_WGSL = `struct Unit { x: f32, y: f32, vx: f32, vy: f32 } @group(0) @binding(0) var<storage, read_write> units: array<Unit>; @group(0) @binding(1) var<storage, read> directions: array<vec2<f32>>; @compute @workgroup_size(64) fn main(@builtin(global_invocation_id) id: vec3<u32>) { if (id.x >= arrayLength(&units)) { return; } let cell = u32(units[id.x].y) * 64u + u32(units[id.x].x); units[id.x].vx = directions[cell].x; units[id.x].vy = directions[cell].y; }`;
export function generateTacticsMap(seed = 0x54414354, width = 48, height = 32): TacticsMap { const w = clampInt(width, 16, 64); const h = clampInt(height, 16, 64); const terrain = new Uint8Array(w * h); const resources = new Uint16Array(w * h); let state = seed | 0; for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { state = xorshift(state); const edge = x === 0 || y === 0 || x === w - 1 || y === h - 1; terrain[y*w+x] = edge || ((state >>> 24) < 18 && x > 6 && x < w - 7) ? 1 : 0; if (!terrain[y*w+x] && ((state >>> 16) & 255) < 12) resources[y*w+x] = 250; } clear(terrain,w,2,2,5); clear(terrain,w,w-7,h-7,5); return { width:w,height:h,terrain,resources }; }
export function buildFlowField(map: TacticsMap, target: GridPoint) { const size = map.width * map.height; const cost = new Uint16Array(size); cost.fill(0xffff); const directions = new Int8Array(size * 2); const tx = clampInt(target.x,0,map.width-1); const ty = clampInt(target.y,0,map.height-1); const start = ty*map.width+tx; if (map.terrain[start]) return { cost, directions }; const queue = new Int32Array(size); let head=0,tail=0; queue[tail++]=start; cost[start]=0; while(head<tail){ const current=queue[head++]; const x=current%map.width,y=Math.floor(current/map.width); for(const [dx,dy] of CARDINAL){ const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=map.width||ny>=map.height)continue;const next=ny*map.width+nx;if(map.terrain[next]||cost[next]!==0xffff)continue;cost[next]=cost[current]+1;directions[next*2]=-dx;directions[next*2+1]=-dy;queue[tail++]=next; } } return { cost, directions }; }
export function dispatchUnits(units: Float32Array, field: Int8Array, mapWidth: number, count = units.length / 4) { const safe=Math.min(Math.floor(count),Math.floor(units.length/4),10000); for(let index=0;index<safe;index++){const offset=index*4;const x=clampInt(units[offset],0,mapWidth-1);const y=Math.max(0,Math.floor(units[offset+1]));const cell=(y*mapWidth+x)*2;if(cell+1>=field.length)continue;units[offset+2]=field[cell];units[offset+3]=field[cell+1];} return safe; }
export function findPathAStar(map:TacticsMap,start:GridPoint,target:GridPoint,maxNodes=4096){const origin=key(start.x,start.y,map.width),goal=key(target.x,target.y,map.width);const open=[origin];const came=new Int32Array(map.width*map.height);came.fill(-1);const g=new Float32Array(came.length);g.fill(Infinity);g[origin]=0;let visited=0;while(open.length&&visited++<maxNodes){open.sort((a,b)=>score(a,g,target,map.width)-score(b,g,target,map.width));const current=open.shift()!;if(current===goal)return reconstruct(came,current,map.width);const x=current%map.width,y=Math.floor(current/map.width);for(const[dx,dy]of CARDINAL){const nx=x+dx,ny=y+dy;if(nx<0||ny<0||nx>=map.width||ny>=map.height)continue;const next=key(nx,ny,map.width);if(map.terrain[next])continue;const candidate=g[current]+1;if(candidate>=g[next])continue;came[next]=current;g[next]=candidate;if(!open.includes(next))open.push(next);}}return[];}
export function fogMask(map:TacticsMap,units:Float32Array,count:number,radius=5){const visible=new Uint8Array(map.width*map.height);for(let i=0;i<Math.min(count,units.length/4);i++){const ux=Math.floor(units[i*4]),uy=Math.floor(units[i*4+1]);for(let y=Math.max(0,uy-radius);y<=Math.min(map.height-1,uy+radius);y++)for(let x=Math.max(0,ux-radius);x<=Math.min(map.width-1,ux+radius);x++)if((x-ux)**2+(y-uy)**2<=radius*radius)visible[y*map.width+x]=1;}return visible;}
const CARDINAL=[[1,0],[-1,0],[0,1],[0,-1]] as const;function clear(terrain:Uint8Array,width:number,x:number,y:number,size:number){for(let yy=y;yy<y+size;yy++)for(let xx=x;xx<x+size;xx++)terrain[yy*width+xx]=0;}function xorshift(value:number){value^=value<<13;value^=value>>>17;value^=value<<5;return value|0;}function clampInt(value:number,min:number,max:number){return Math.max(min,Math.min(max,Math.floor(Number.isFinite(value)?value:min)));}function key(x:number,y:number,width:number){return y*width+x;}function score(index:number,g:Float32Array,target:GridPoint,width:number){return g[index]+Math.abs(index%width-target.x)+Math.abs(Math.floor(index/width)-target.y);}function reconstruct(came:Int32Array,current:number,width:number){const path:GridPoint[]=[];while(current>=0){path.push({x:current%width,y:Math.floor(current/width)});current=came[current];}return path.reverse();}
