import { expect, test, type Page } from '@playwright/test';

test.beforeEach(async ({ page }) => { await page.addInitScript(() => { let state = 0x43594252; Math.random = () => { state ^= state << 13; state ^= state >>> 17; state ^= state << 5; return (state >>> 0) / 4294967296; }; localStorage.setItem('bios_arcade_free_play', 'true'); }); });

test('select a compute backend and render a stable raycaster frame', async ({ page }) => { await page.goto('/'); await page.locator('#app canvas').first().waitFor(); await expect.poll(() => page.evaluate(() => document.documentElement.dataset.compute)).toMatch(/webgpu|worker|wasm|cpu/); await launchGame(page, 12, 'RaycasterScene'); await page.evaluate(() => (window as typeof window & { game: { scene: { pause(key: string): void } } }).game.scene.pause('RaycasterScene')); const first = await page.locator('#app canvas').first().screenshot(); await page.waitForTimeout(100); const second = await page.locator('#app canvas').first().screenshot(); expect(second.equals(first)).toBe(true); });

test('compile and sign a visual graph without executable code', async ({ page }) => { await page.goto('/'); await page.locator('#app canvas').first().waitFor(); await page.keyboard.press('v'); await expect(page.locator('.visual-studio')).toBeVisible(); await page.locator('[data-node="EVENT"]').click(); await page.locator('[data-node="HAZARD"]').click(); await page.locator('[data-compile]').click(); await expect.poll(() => page.locator('[data-output]').inputValue()).toContain('"sha256"'); expect(await page.locator('[data-output]').inputValue()).not.toContain('function'); });

test('bound heap growth across rapid scene mount and unmount cycles', async ({ page, context }) => { await page.goto('/'); await page.locator('#app canvas').first().waitFor(); await launchGame(page, 12, 'RaycasterScene'); const session = await context.newCDPSession(page); await session.send('Performance.enable'); await session.send('HeapProfiler.enable'); await session.send('HeapProfiler.collectGarbage'); const before = await heapUsed(session); for (let cycle = 0; cycle < 12; cycle++) await page.evaluate(() => { const game = (window as typeof window & { game: { scene: { start(key: string, data?: unknown): void } } }).game; game.scene.start('LobbyScene'); game.scene.start('RaycasterScene', { difficulty: 'NORMAL', mode: 'SOLO' }); }); await page.evaluate(() => (window as typeof window & { game: { scene: { start(key: string): void } } }).game.scene.start('LobbyScene')); await session.send('HeapProfiler.collectGarbage'); const after = await heapUsed(session); expect(after - before).toBeLessThan(16 * 1024 * 1024); });

async function launchGame(page: Page, index: number, key: string) { await page.evaluate(({ index }) => { const lobby = (window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('LobbyScene') as { updateGameSelection(change: number): void; handleSpace(): void }; for (let step = 0; step < index; step++) lobby.updateGameSelection(1); lobby.handleSpace(); }, { index }); await page.waitForTimeout(220); await page.evaluate(() => ((window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('LobbyScene') as { handleSpace(): void }).handleSpace()); await expect.poll(() => page.evaluate(key => Boolean((window as typeof window & { game: { scene: { isActive(sceneKey: string): boolean } } }).game.scene.isActive(key)), key), { timeout: 10000 }).toBe(true); }
async function heapUsed(session: Awaited<ReturnType<import('@playwright/test').BrowserContext['newCDPSession']>>) { const metrics = await session.send('Performance.getMetrics'); return Number((metrics.metrics as Array<{ name: string; value: number }>).find(metric => metric.name === 'JSHeapUsedSize')?.value ?? 0); }
