import { expect, test, type Page } from '@playwright/test';

test.beforeEach(async ({ page }) => { await page.addInitScript(() => { let state = 0x47454e53; Math.random = () => { state ^= state << 13; state ^= state >>> 17; state ^= state << 5; return (state >>> 0) / 4294967296; }; localStorage.setItem('bios_arcade_free_play', 'true'); }); });

test('stabilize 1,000 generations and correlate observed resource branches', async ({ page }) => { await launchGenesis(page); const runtime = await page.evaluate(() => ((window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('GenesisScene') as { genesisRuntime(): { generation: number; backend: string } }).genesisRuntime()), result = await diagnostics(page); expect(runtime.backend).toBe('WORKER'); expect(runtime.generation).toBeGreaterThan(0); expect(result.generations).toBe(1000); expect(result.fitness).toBeGreaterThan(.5); expect(result.diversity).toBeGreaterThanOrEqual(0); expect(result.quantumBranch).toBe(result.entangledBranch); expect(result.agents).toBe(8); });

test('reach deterministic society consensus and render a stable universe frame', async ({ page }) => { await launchGenesis(page); const result = await diagnostics(page), gpu = await page.evaluate(() => ((window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('GenesisScene') as { genesisGpuDiagnostics(): Promise<string> }).genesisGpuDiagnostics()); expect(['TRADE', 'ALLY', 'OBSERVE', 'MIGRATE']).toContain(result.consensus); expect(result.leader).toMatch(/^agent-/); expect(['COMPILED', 'UNAVAILABLE']).toContain(gpu); await page.evaluate(() => (window as typeof window & { game: { scene: { pause(key: string): void } } }).game.scene.pause('GenesisScene')); const first = await page.locator('#app canvas').first().screenshot(), second = await page.locator('#app canvas').first().screenshot(); expect(first.equals(second)).toBe(true); });

async function diagnostics(page: Page) { return page.evaluate(() => ((window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('GenesisScene') as { genesisDiagnostics(): Promise<{ generations: number; fitness: number; diversity: number; quantumBranch: number; entangledBranch?: number; consensus: string; leader: string; agents: number }> }).genesisDiagnostics()); }
async function launchGenesis(page: Page) { await page.goto('/'); await page.locator('#app canvas').first().waitFor(); await page.evaluate(() => { const lobby = (window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('LobbyScene') as { updateGameSelection(change: number): void; handleSpace(): void }; for (let index = 0; index < 24; index++) lobby.updateGameSelection(1); lobby.handleSpace(); }); await page.waitForTimeout(220); await page.evaluate(() => ((window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('LobbyScene') as { handleSpace(): void }).handleSpace()); await expect.poll(() => page.evaluate(() => (window as typeof window & { game: { scene: { isActive(key: string): boolean } } }).game.scene.isActive('GenesisScene'))).toBe(true); await expect.poll(() => page.evaluate(() => ((window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('GenesisScene') as { genesisRuntime(): { generation: number } }).genesisRuntime().generation)).toBeGreaterThan(0); }
