import { expect, test, type Page } from '@playwright/test';

test.beforeEach(async ({ page }) => { await page.addInitScript(() => { localStorage.setItem('bios_arcade_free_play', 'true'); let state = 0x53494e47; Math.random = () => { state ^= state << 13; state ^= state >>> 17; state ^= state << 5; return (state >>> 0) / 4294967296; }; }); });

async function launchSingularity(page: Page) { await page.goto('/'); await page.locator('#app canvas').first().waitFor(); await page.evaluate(() => { const lobby = (window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('LobbyScene') as { updateGameSelection(change: number): void; handleSpace(): void }; for (let index = 0; index < 26; index++) lobby.updateGameSelection(1); lobby.handleSpace(); }); await page.waitForTimeout(220); await page.evaluate(() => ((window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('LobbyScene') as { handleSpace(): void }).handleSpace()); await expect.poll(() => page.evaluate(() => Boolean((window as typeof window & { game?: { scene: { isActive(key: string): boolean } } }).game?.scene.isActive('SingularityScene'))), { timeout: 10_000 }).toBe(true); }

test('validate neural terrain, path tracing, and authenticated consensus diagnostics', async ({ page }) => { await launchSingularity(page); const result = await page.evaluate(() => ((window as typeof window & { game: { scene: { getScene(key: string): unknown } } }).game.scene.getScene('SingularityScene') as { singularityDiagnostics(): Promise<{ terrainChecksum: number; lightChecksum: number; architectures: number; stateRoot: string; chainValid: boolean; gridShards: number; societyAgents: number; terrainGpu: string; pathGpu: string; broadcast: boolean; xr: { vr: boolean; ar: boolean } }> }).singularityDiagnostics()); expect(result.terrainChecksum).toBeGreaterThan(0); expect(result.lightChecksum).toBeGreaterThan(0); expect(result.architectures).toBe(17); expect(result.stateRoot).toMatch(/^[a-f0-9]{64}$/); expect(result.chainValid).toBe(true); expect(result.gridShards).toBe(4); expect(result.societyAgents).toBe(8); expect(['COMPILED', 'UNAVAILABLE']).toContain(result.terrainGpu); expect(['COMPILED', 'UNAVAILABLE']).toContain(result.pathGpu); expect(typeof result.broadcast).toBe('boolean'); expect(typeof result.xr.vr).toBe('boolean'); });

test('hold a byte-identical denoised world frame after pausing', async ({ page }) => { await launchSingularity(page); await page.evaluate(() => (window as typeof window & { game: { scene: { pause(key: string): void } } }).game.scene.pause('SingularityScene')); const first = await page.locator('#app canvas').first().screenshot(), second = await page.locator('#app canvas').first().screenshot(); expect(first.equals(second)).toBe(true); });
