import Phaser from 'phaser';
import { InputManager } from '../../engine/InputManager';
import { AudioEngine } from '../../engine/AudioEngine';
import { CellularFluid, solveFabrik, type Joint } from '../../graphics/kinematics/Kinematics';
import { canEnter, ChunkCache, type Ability, type LabyrinthChunk } from './LabyrinthSystems';
export default class NeonLabyrinthScene extends Phaser.Scene {
  private gfx!: Phaser.GameObjects.Graphics; private hud!: Phaser.GameObjects.Text; private chunkCache = new ChunkCache(); private chunk!: LabyrinthChunk; private roomX = 0; private roomY = 0; private x = 48; private y = 320; private vx = 0; private vy = 0; private jumps = 0; private abilities = new Set<Ability>(); private fluid = new CellularFluid(32, 24); private bossHealth = 12; private fireHeld = false;
  constructor() { super('LabyrinthScene'); }
  create() { this.roomX = 0; this.roomY = 0; this.x = 48; this.y = 320; this.vx = 0; this.vy = 0; this.abilities.clear(); this.loadRoom(); this.gfx = this.add.graphics(); this.hud = this.add.text(10, 8, '', { fontFamily: 'Courier', fontSize: '13px', color: '#fff' }).setDepth(5); this.add.text(320, 16, 'NEON LABYRINTH // METROIDVANIA CORE', { fontFamily: 'Courier', fontSize: '17px', color: '#ff2ec4', fontStyle: 'bold' }).setOrigin(.5).setDepth(5); this.input.keyboard?.on('keydown-ESC', () => this.scene.start('LobbyScene')); AudioEngine.playTrack('labyrinth'); }
  update(_time: number, delta: number) { const dt = Math.min(50, delta) / 1000; const left = InputManager.isP1Down('LEFT'), right = InputManager.isP1Down('RIGHT'), jump = InputManager.isP1Down('FIRE'); this.vx = (left === right ? 0 : left ? -1 : 1) * 150; if (InputManager.isDown('ShiftLeft') && this.abilities.has('DASH')) this.vx *= 2.4; if (jump && !this.fireHeld && (this.jumps < 1 || this.abilities.has('DOUBLE_JUMP') && this.jumps < 2)) { this.vy = -270; this.jumps++; } this.fireHeld = jump; this.vy += 620 * dt; this.x += this.vx * dt; this.y += this.vy * dt; if (this.y >= 430) { this.y = 430; this.vy = 0; this.jumps = 0; } if (this.abilities.has('WALL_CLING') && (this.x < 12 || this.x > 628) && this.vy > 60) this.vy = 60; if (this.x < 0) this.transition(-1); else if (this.x > 640) this.transition(1); const reward = this.chunk.reward; if (reward && !this.abilities.has(reward) && this.x > 280 && this.x < 360) { this.abilities.add(reward); AudioEngine.playEffect('POWER_UP'); } if (this.chunk.boss && jump && this.x > 470) this.bossHealth = Math.max(0, this.bossHealth - 1); this.fluid.step(this.chunk.tiles); this.draw(); }
  private transition(direction: number) { const next = this.chunkCache.get(this.roomX + direction, this.roomY); if (!canEnter(next, this.abilities)) { this.x = direction > 0 ? 620 : 20; this.vx = 0; return; } this.roomX += direction; this.chunk = next; this.x = direction > 0 ? 8 : 632; this.seedFluid(); }
  private loadRoom() { this.chunk = this.chunkCache.get(this.roomX, this.roomY); this.seedFluid(); }
  private seedFluid() { this.fluid = new CellularFluid(32, 24); for (let x = 10; x < 22; x++) this.fluid.seed(x, 2, 180); }
  private draw() { this.gfx.clear().fillStyle(0x050311).fillRect(0, 0, 640, 480); for (let y = 0; y < 24; y++) for (let x = 0; x < 32; x++) { const index = y * 32 + x; if (this.chunk.tiles[index]) this.gfx.fillStyle(0x24204a).fillRect(x * 20, y * 20, 20, 20); const fluid = this.fluid.cells[index]; if (fluid) this.gfx.fillStyle(0xff3300, fluid / 255 * .8).fillRect(x * 20, y * 20 + 10, 20, 10); } if (this.chunk.reward && !this.abilities.has(this.chunk.reward)) this.gfx.fillStyle(0x00ffcc).fillCircle(320, 390, 12); if (this.chunk.boss && this.bossHealth > 0) this.drawBoss(); this.gfx.fillStyle(0xff2ec4).fillRect(this.x - 8, this.y - 18, 16, 36); this.hud.setText(`ZONE ${this.roomX},${this.roomY}  ABILITIES ${[...this.abilities].join(' ') || 'NONE'}  ${this.chunk.gate ? `GATE ${this.chunk.gate}` : ''}`); }
  private drawBoss() { const center = { x: 520, y: 300 }; this.gfx.fillStyle(0xff2255).fillCircle(center.x, center.y, 34); for (let leg = 0; leg < 6; leg++) { const angle = leg / 6 * Math.PI * 2; const joints: Joint[] = [center, { x: center.x + Math.cos(angle) * 45, y: center.y + Math.sin(angle) * 45 }, { x: center.x + Math.cos(angle) * 90, y: center.y + Math.sin(angle) * 90 }]; const solved = solveFabrik(joints, [50, 55], { x: this.x + (leg - 3) * 18, y: this.y }, 5); this.gfx.lineStyle(5, 0xff2255).beginPath().moveTo(solved[0].x, solved[0].y).lineTo(solved[1].x, solved[1].y).lineTo(solved[2].x, solved[2].y).strokePath(); } }
}
