import Phaser from 'phaser';
import { AudioEngine } from '../../engine/AudioEngine';
import { InputManager } from '../../engine/InputManager';
import { SaveManager } from '../../engine/SaveManager';
import type { ArcadeMode } from '../../multiplayer/CoopSession';
import { canOccupy, castRay, generateBspDungeon, wallPattern, type Dungeon } from './RaycasterSystems';

interface SpriteEntity { x: number; y: number; kind: 'ENEMY' | 'CORE' | 'EXIT'; health: number; }
export default class NeonCyberCasterScene extends Phaser.Scene {
  private view!: Phaser.GameObjects.Graphics; private hud!: Phaser.GameObjects.Text; private dungeon!: Dungeon; private entities: SpriteEntity[] = []; private x = 2.5; private y = 2.5; private angle = 0; private level = 1; private score = 0; private health = 100; private fireHeld = false; private difficulty = 'NORMAL'; private mode: ArcadeMode = 'SOLO'; private readonly rays = 160; private readonly fov = Math.PI / 3; private zBuffer = new Float32Array(160);
  constructor() { super('RaycasterScene'); }
  create(data: { difficulty?: string; mode?: ArcadeMode; level?: number; score?: number }) { this.difficulty = data.difficulty ?? 'NORMAL'; this.mode = data.mode ?? 'SOLO'; this.level = data.level ?? 1; this.score = data.score ?? 0; this.health = 100; this.fireHeld = false; this.dungeon = generateBspDungeon(this.level); this.x = this.dungeon.spawn.x; this.y = this.dungeon.spawn.y; this.angle = 0; this.entities = this.makeEntities(); this.view = this.add.graphics(); this.hud = this.add.text(12, 10, '', { fontFamily: 'Courier', fontSize: '13px', color: '#ffffff' }).setDepth(20); this.add.text(320, 15, 'NEON CYBER-CASTER // DDA CORE', { fontFamily: 'Courier', fontSize: '18px', color: '#00ffcc', fontStyle: 'bold' }).setOrigin(0.5).setDepth(20); this.add.text(628, 42, 'MOVE W/S  TURN A/D  FIRE SPACE  ESC PAUSE', { fontFamily: 'Courier', fontSize: '9px', color: '#779999' }).setOrigin(1, 0).setDepth(20); this.input.keyboard?.on('keydown-ESC', () => { this.scene.pause(); this.scene.launch('PauseScene', { scene: this.scene.key }); }); AudioEngine.playTrack('caster'); }
  update(_time: number, delta: number) { const dt = Math.min(delta, 50) / 1000; const turn = InputManager.isP1Down('LEFT') === InputManager.isP1Down('RIGHT') ? 0 : InputManager.isP1Down('LEFT') ? -1 : 1; const move = InputManager.isP1Down('UP') === InputManager.isP1Down('DOWN') ? 0 : InputManager.isP1Down('UP') ? 1 : -0.7; this.angle += turn * dt * 2.1; const speed = move * dt * (this.difficulty === 'EXPERT' ? 3.1 : 2.6); const nextX = this.x + Math.cos(this.angle) * speed; const nextY = this.y + Math.sin(this.angle) * speed; if (canOccupy(this.dungeon, nextX, this.y)) this.x = nextX; if (canOccupy(this.dungeon, this.x, nextY)) this.y = nextY; const fire = InputManager.isP1Down('FIRE'); if (fire && !this.fireHeld) this.fire(); this.fireHeld = fire; this.updateEnemies(dt); this.renderWorld(); this.hud.setText(`SCORE ${this.score}  LEVEL ${this.level}  HEALTH ${Math.ceil(this.health)}  HOSTILES ${this.entities.filter(entity => entity.kind === 'ENEMY').length}`); if (this.health <= 0) this.finish(); }
  private renderWorld() { const width = 640; const height = 480; const strip = width / this.rays; this.view.clear().fillStyle(0x08021a).fillRect(0, 0, width, height / 2).fillStyle(0x080b12).fillRect(0, height / 2, width, height / 2); for (let ray = 0; ray < this.rays; ray++) { const rayAngle = this.angle - this.fov / 2 + ray / this.rays * this.fov; const hit = castRay(this.dungeon, this.x, this.y, rayAngle); const corrected = hit.distance * Math.cos(rayAngle - this.angle); this.zBuffer[ray] = corrected; const wallHeight = Math.min(height, height / corrected); const top = (height - wallHeight) / 2; const shade = wallPattern(hit.mapX, hit.mapY, hit.textureX, 0.5, this.level) * Math.max(0.18, 1 - corrected / 18) * (hit.side ? 0.75 : 1); const red = Math.floor(20 + shade * 40); const green = Math.floor(60 + shade * 170); const blue = Math.floor(80 + shade * 175); this.view.fillStyle((red << 16) | (green << 8) | blue).fillRect(ray * strip, top, Math.ceil(strip + 1), wallHeight); for (let band = 0; band < 8; band++) { const bandY = top + band / 8 * wallHeight; const pattern = wallPattern(hit.mapX, hit.mapY, hit.textureX, band / 8, this.level); if (pattern < 0.55) this.view.fillStyle(0x02070a, 0.4).fillRect(ray * strip, bandY, Math.ceil(strip + 1), Math.max(1, wallHeight / 40)); } } this.renderSprites(); this.view.lineStyle(1, 0x00ffcc, 0.5).strokeCircle(320, 240, 5).lineBetween(312, 240, 328, 240).lineBetween(320, 232, 320, 248); }
  private renderSprites() { const visible = this.entities.map(entity => { const dx = entity.x - this.x; const dy = entity.y - this.y; return { entity, distance: Math.hypot(dx, dy), relative: wrapAngle(Math.atan2(dy, dx) - this.angle) }; }).filter(item => Math.abs(item.relative) < this.fov * 0.65).sort((a, b) => b.distance - a.distance); for (const item of visible) { const screenX = 320 + item.relative / (this.fov / 2) * 320; const ray = Math.max(0, Math.min(this.rays - 1, Math.floor(screenX / 640 * this.rays))); if (item.distance > this.zBuffer[ray] + 0.4) continue; const size = Math.min(220, 210 / Math.max(0.3, item.distance)); const color = item.entity.kind === 'ENEMY' ? 0xff2255 : item.entity.kind === 'CORE' ? 0xffff00 : 0x00ff88; this.view.fillStyle(color, Math.max(0.25, 1 - item.distance / 20)).fillRect(screenX - size / 2, 240 - size / 2, size, size); if (item.entity.kind === 'ENEMY') this.view.fillStyle(0xffffff).fillRect(screenX - size * 0.22, 240 - size * 0.12, size * 0.12, size * 0.12).fillRect(screenX + size * 0.1, 240 - size * 0.12, size * 0.12, size * 0.12); } }
  private fire() { const candidates = this.entities.filter(entity => entity.kind === 'ENEMY').map(entity => ({ entity, distance: Math.hypot(entity.x - this.x, entity.y - this.y), angle: Math.abs(wrapAngle(Math.atan2(entity.y - this.y, entity.x - this.x) - this.angle)) })).filter(candidate => candidate.angle < 0.08).sort((a, b) => a.distance - b.distance); const target = candidates[0]; if (target && target.distance < castRay(this.dungeon, this.x, this.y, this.angle).distance) { target.entity.health--; this.score += 50; if (target.entity.health <= 0) { this.entities = this.entities.filter(entity => entity !== target.entity); this.score += 250; AudioEngine.playEffect('EXPLOSION'); } else AudioEngine.playEffect('LASER'); } else AudioEngine.playEffect('LASER'); this.cameras.main.shake(45, 0.003); }
  private updateEnemies(dt: number) { for (const enemy of this.entities.filter(entity => entity.kind === 'ENEMY')) { const distance = Math.hypot(enemy.x - this.x, enemy.y - this.y); if (distance < 7 && distance > 0.7) { const speed = dt * (0.45 + this.level * 0.025); const nx = enemy.x + (this.x - enemy.x) / distance * speed; const ny = enemy.y + (this.y - enemy.y) / distance * speed; if (canOccupy(this.dungeon, nx, enemy.y, 0.12)) enemy.x = nx; if (canOccupy(this.dungeon, enemy.x, ny, 0.12)) enemy.y = ny; } if (distance < 0.75) this.health -= dt * (8 + this.level); } for (const entity of [...this.entities]) if (Math.hypot(entity.x - this.x, entity.y - this.y) < 0.55) { if (entity.kind === 'CORE') { this.health = Math.min(100, this.health + 25); this.score += 100; this.entities = this.entities.filter(candidate => candidate !== entity); AudioEngine.playEffect('POWER_UP'); } else if (entity.kind === 'EXIT' && !this.entities.some(candidate => candidate.kind === 'ENEMY')) this.scene.restart({ difficulty: this.difficulty, mode: this.mode, level: this.level + 1, score: this.score + 500 }); } }
  private makeEntities() { const entities: SpriteEntity[] = []; for (let index = 1; index < this.dungeon.rooms.length; index++) { const room = this.dungeon.rooms[index]; const x = room.x + room.width / 2; const y = room.y + room.height / 2; entities.push({ x, y, kind: index % 3 === 0 ? 'CORE' : 'ENEMY', health: 1 + Math.floor(this.level / 4) }); } entities.push({ ...this.dungeon.exit, kind: 'EXIT', health: 1 }); return entities; }
  private finish() { this.scene.pause(); SaveManager.submitScore('RaycasterScene', `${this.difficulty}-${this.mode}`, this.score); const panel = this.add.text(320, 240, `SYSTEM BREACH\nSCORE ${this.score}\nLEVEL ${this.level}\nCLICK TO REBOOT`, { fontFamily: 'Courier', fontSize: '27px', color: '#ff2255', align: 'center', backgroundColor: '#000000dd', padding: { x: 18, y: 14 } }).setOrigin(0.5).setDepth(30).setInteractive(); panel.on('pointerdown', () => this.scene.restart({ difficulty: this.difficulty, mode: this.mode })); }
}
function wrapAngle(value: number) { let angle = value; while (angle > Math.PI) angle -= Math.PI * 2; while (angle < -Math.PI) angle += Math.PI * 2; return angle; }
