export interface Dungeon { width: number; height: number; cells: Uint8Array; rooms: Room[]; spawn: { x: number; y: number }; exit: { x: number; y: number }; }
export interface Room { x: number; y: number; width: number; height: number; }
export interface RayHit { distance: number; mapX: number; mapY: number; side: 0 | 1; textureX: number; }

export function generateBspDungeon(level: number, width = 24, height = 24, seed = 0x43594252): Dungeon { const safeWidth = clampInt(width, 12, 64); const safeHeight = clampInt(height, 12, 64); const random = seeded(seed ^ Math.imul(Math.max(1, Math.floor(level)), 0x9e3779b1)); const leaves: Room[] = []; split({ x: 1, y: 1, width: safeWidth - 2, height: safeHeight - 2 }, 0, random, leaves); const rooms = leaves.map(leaf => { const marginX = 1 + Math.floor(random() * Math.max(1, Math.min(3, leaf.width - 4))); const marginY = 1 + Math.floor(random() * Math.max(1, Math.min(3, leaf.height - 4))); return { x: leaf.x + marginX, y: leaf.y + marginY, width: Math.max(3, leaf.width - marginX - 1), height: Math.max(3, leaf.height - marginY - 1) }; }); const cells = new Uint8Array(safeWidth * safeHeight); cells.fill(1); for (const room of rooms) carveRoom(cells, safeWidth, room); for (let index = 1; index < rooms.length; index++) connect(cells, safeWidth, center(rooms[index - 1]), center(rooms[index]), random() < 0.5); const first = center(rooms[0]); const last = center(rooms[rooms.length - 1]); return { width: safeWidth, height: safeHeight, cells, rooms, spawn: { x: first.x + 0.5, y: first.y + 0.5 }, exit: { x: last.x + 0.5, y: last.y + 0.5 } }; }

export function castRay(dungeon: Pick<Dungeon, 'width' | 'height' | 'cells'>, x: number, y: number, angle: number, maxDistance = 64): RayHit { const directionX = Math.cos(angle); const directionY = Math.sin(angle); let mapX = Math.floor(x); let mapY = Math.floor(y); const deltaX = Math.abs(1 / (directionX || 1e-9)); const deltaY = Math.abs(1 / (directionY || 1e-9)); const stepX = directionX < 0 ? -1 : 1; const stepY = directionY < 0 ? -1 : 1; let sideX = directionX < 0 ? (x - mapX) * deltaX : (mapX + 1 - x) * deltaX; let sideY = directionY < 0 ? (y - mapY) * deltaY : (mapY + 1 - y) * deltaY; let side: 0 | 1 = 0; for (let step = 0; step < maxDistance * 2; step++) { if (sideX < sideY) { sideX += deltaX; mapX += stepX; side = 0; } else { sideY += deltaY; mapY += stepY; side = 1; } if (mapX < 0 || mapY < 0 || mapX >= dungeon.width || mapY >= dungeon.height || dungeon.cells[mapY * dungeon.width + mapX]) { const distance = Math.max(0.0001, side === 0 ? sideX - deltaX : sideY - deltaY); const wall = side === 0 ? y + distance * directionY : x + distance * directionX; return { distance, mapX, mapY, side, textureX: wall - Math.floor(wall) }; } } return { distance: maxDistance, mapX, mapY, side, textureX: 0 }; }

export function wallPattern(mapX: number, mapY: number, textureX: number, textureY: number, seed = 0x57414c4c) { const x = Math.floor(textureX * 32); const y = Math.floor(textureY * 32); let value = Math.imul(mapX + seed, 374761393) ^ Math.imul(mapY, 668265263) ^ Math.imul(x, 2246822519) ^ Math.imul(y, 3266489917); value ^= value >>> 13; value = Math.imul(value, 1274126177); const cellular = ((x % 8 === 0) || (y % 8 === 0)) ? 0.35 : 1; return (0.55 + (value >>> 24) / 255 * 0.45) * cellular; }
export function canOccupy(dungeon: Pick<Dungeon, 'width' | 'height' | 'cells'>, x: number, y: number, radius = 0.18) { for (const ox of [-radius, radius]) for (const oy of [-radius, radius]) { const cellX = Math.floor(x + ox); const cellY = Math.floor(y + oy); if (cellX < 0 || cellY < 0 || cellX >= dungeon.width || cellY >= dungeon.height || dungeon.cells[cellY * dungeon.width + cellX]) return false; } return true; }
function split(area: Room, depth: number, random: () => number, output: Room[]) { if (depth >= 4 || area.width < 11 || area.height < 11) { output.push(area); return; } const vertical = area.width > area.height ? true : area.height > area.width ? false : random() < 0.5; const dimension = vertical ? area.width : area.height; const cut = Math.floor(dimension * (0.38 + random() * 0.24)); if (vertical) { split({ ...area, width: cut }, depth + 1, random, output); split({ x: area.x + cut, y: area.y, width: area.width - cut, height: area.height }, depth + 1, random, output); } else { split({ ...area, height: cut }, depth + 1, random, output); split({ x: area.x, y: area.y + cut, width: area.width, height: area.height - cut }, depth + 1, random, output); } }
function carveRoom(cells: Uint8Array, width: number, room: Room) { for (let y = room.y; y < room.y + room.height; y++) for (let x = room.x; x < room.x + room.width; x++) cells[y * width + x] = 0; }
function connect(cells: Uint8Array, width: number, a: { x: number; y: number }, b: { x: number; y: number }, horizontalFirst: boolean) { const carveX = () => { for (let x = Math.min(a.x, b.x); x <= Math.max(a.x, b.x); x++) cells[a.y * width + x] = 0; }; const carveY = () => { for (let y = Math.min(a.y, b.y); y <= Math.max(a.y, b.y); y++) cells[y * width + b.x] = 0; }; if (horizontalFirst) { carveX(); carveY(); } else { for (let y = Math.min(a.y, b.y); y <= Math.max(a.y, b.y); y++) cells[y * width + a.x] = 0; for (let x = Math.min(a.x, b.x); x <= Math.max(a.x, b.x); x++) cells[b.y * width + x] = 0; } }
function center(room: Room) { return { x: room.x + Math.floor(room.width / 2), y: room.y + Math.floor(room.height / 2) }; }
function seeded(seed: number) { let state = seed | 0 || 1; return () => { state ^= state << 13; state ^= state >>> 17; state ^= state << 5; return (state >>> 0) / 4294967296; }; }
function clampInt(value: number, minimum: number, maximum: number) { return Math.max(minimum, Math.min(maximum, Math.floor(value))); }
