import Phaser from 'phaser';
import { AiDirector, type DirectorDecision } from '../../ai/director/AiDirector';
import { AudioEngine } from '../../engine/AudioEngine';
import { ProjectileEcs } from '../../engine/ecs/ProjectileEcs';
import { FrameTelemetry } from '../../engine/FrameTelemetry';
import { InputManager } from '../../engine/InputManager';
import { solveFabrik, type Joint } from '../../graphics/kinematics/Kinematics';
import { emitFibonacciSpiral, emitHomingFan, emitPolygon, scriptedBossPhase } from './DanmakuPatterns';

export default class NeonDanmakuScene extends Phaser.Scene {
  readonly projectiles = new ProjectileEcs(100_000); private readonly director = new AiDirector(); private readonly telemetry = new FrameTelemetry(120); private gfx!: Phaser.GameObjects.Graphics; private hud!: Phaser.GameObjects.Text; private playerX = 320; private playerY = 430; private bossX = 320; private bossY = 92; private stage = 1; private score = 0; private lives = 3; private elapsed = 0; private nextWave = 0; private phase = 0; private decision: DirectorDecision = { density: .3, speed: .35, powerUpChance: .1, pattern: 'SPIRAL', pressure: .5 }; private shots = 0; private hits = 0; private damage = 0;
  constructor() { super('DanmakuScene'); }
  create() { this.projectiles.clear(); this.playerX = 320; this.playerY = 430; this.stage = 1; this.score = 0; this.lives = 3; this.elapsed = 0; this.nextWave = 0; this.phase = 0; this.gfx = this.add.graphics(); this.hud = this.add.text(10, 8, '', { fontFamily: 'Courier', fontSize: '13px', color: '#ffffff' }).setDepth(4); this.add.text(320, 18, 'NEON DANMAKU // 100K ECS', { fontFamily: 'Courier', fontSize: '18px', color: '#ff2ec4', fontStyle: 'bold' }).setOrigin(.5).setDepth(4); this.input.keyboard?.on('keydown-ESC', () => this.scene.start('LobbyScene')); AudioEngine.playTrack('danmaku'); }
  update(time: number, delta: number) { const dt = Math.min(50, delta) / 1000; this.elapsed += dt; this.telemetry.record(delta); const dx = Number(InputManager.isP1Down('RIGHT')) - Number(InputManager.isP1Down('LEFT')), dy = Number(InputManager.isP1Down('DOWN')) - Number(InputManager.isP1Down('UP')); const focus = InputManager.isP1Down('FIRE') ? .45 : 1; this.playerX = Phaser.Math.Clamp(this.playerX + dx * 220 * focus * dt, 12, 628); this.playerY = Phaser.Math.Clamp(this.playerY + dy * 220 * focus * dt, 48, 468); this.decision = this.director.update(time, { damageRate: Math.min(1, this.damage / Math.max(1, this.elapsed / 10)), accuracy: this.hits / Math.max(1, this.shots), movementEntropy: Math.min(1, (Math.abs(dx) + Math.abs(dy)) * .5), nearMissRate: Math.min(1, this.projectiles.activeCount / 18000), lives: this.lives, stage: this.stage }); if (this.elapsed >= this.nextWave) { this.emitWave(); this.nextWave = this.elapsed + Math.max(.08, .32 - this.decision.density * .2); } this.projectiles.update(dt, this.playerX, this.playerY); this.collide(); if (this.elapsed > this.stage * 12) { this.stage++; this.phase = scriptedBossPhase(this.stage); AudioEngine.playEffect('STAGE_CLEAR'); } this.draw(delta); }
  seedDensePattern(count = 25_000) { this.projectiles.clear(); const bounded = Math.max(0, Math.min(100_000, Math.floor(count))); for (let i = 0; i < bounded; i++) { const angle = i * 2.399963229728653; const radius = 16 + i % 180; this.projectiles.spawn({ x: this.bossX + Math.cos(angle) * radius, y: this.bossY + Math.sin(angle) * radius, vx: Math.cos(angle) * 18, vy: Math.sin(angle) * 18 + 20, life: 20, kind: i % 3 as 0 | 1 | 2 }); } return this.projectiles.activeCount; }
  private emitWave() { const count = 8 + Math.floor(this.decision.density * 36), speed = 48 + this.decision.speed * 115, phase = this.elapsed * .7; const kind = this.phase === 0 ? this.decision.pattern : (['SPIRAL','POLYGON','HOMING','MIXED'] as const)[this.phase]; if (kind === 'POLYGON') emitPolygon(this.projectiles, this.bossX, this.bossY, 5 + this.stage % 5, Math.max(1, Math.floor(count / 7)), speed, phase); else if (kind === 'HOMING') emitHomingFan(this.projectiles, this.bossX, this.bossY, count, speed, Math.PI / 2); else { emitFibonacciSpiral(this.projectiles, this.bossX, this.bossY, count, speed, phase); if (kind === 'MIXED') emitHomingFan(this.projectiles, this.bossX, this.bossY, Math.ceil(count / 4), speed * .7); } this.shots += count; }
  private collide() { for (let i = 0; i < this.projectiles.capacity; i++) { if (!this.projectiles.active[i]) continue; const distance = Math.hypot(this.projectiles.x[i] - this.playerX, this.projectiles.y[i] - this.playerY); if (distance < 7) { this.projectiles.kill(i); this.lives--; this.damage++; this.cameras.main.shake(100, .006); AudioEngine.playEffect('EXPLOSION'); if (this.lives <= 0) { this.lives = 3; this.score = Math.max(0, this.score - 1000); } } else if (distance < 18) this.score++; } }
  private draw(delta: number) { const frame = this.telemetry.snapshot(), renderBudget = delta > 20 ? 6000 : 16000, stride = Math.max(1, Math.ceil(this.projectiles.activeCount / renderBudget)); this.gfx.clear().fillStyle(0x03020c).fillRect(0, 0, 640, 480); this.gfx.lineStyle(1, 0x441177, .3); for (let y = 40; y < 480; y += 32) this.gfx.lineBetween(0, y, 640, y); let drawn = 0; for (let i = 0; i < this.projectiles.capacity; i += stride) if (this.projectiles.active[i]) { const color = this.projectiles.kind[i] === 2 ? 0xff3355 : this.projectiles.kind[i] === 1 ? 0x00ffcc : 0xff2ec4; this.gfx.fillStyle(color, .92).fillCircle(this.projectiles.x[i], this.projectiles.y[i], this.projectiles.kind[i] === 2 ? 3 : 2); drawn++; } this.drawBoss(); this.gfx.fillStyle(0xffffff).fillTriangle(this.playerX, this.playerY - 9, this.playerX - 7, this.playerY + 8, this.playerX + 7, this.playerY + 8); this.gfx.lineStyle(1, 0x00ffcc).strokeCircle(this.playerX, this.playerY, 3); this.hud.setText(`STAGE ${this.stage}  SCORE ${this.score}  LIVES ${this.lives}  BULLETS ${this.projectiles.activeCount}  DRAWN ${drawn}\nDIRECTOR ${this.decision.pattern}  PRESSURE ${this.decision.pressure.toFixed(2)}  FPS ${frame.fps.toFixed(0)}  ${this.projectiles.shared ? 'SHARED' : 'LOCAL'} MEMORY`); }
  private drawBoss() { const center = { x: this.bossX, y: this.bossY }; this.gfx.fillStyle(0x33115e).fillCircle(center.x, center.y, 29); this.gfx.lineStyle(4, 0xff2ec4); for (let limb = 0; limb < 8; limb++) { const angle = limb / 8 * Math.PI * 2 + this.elapsed * .3, target = { x: center.x + Math.cos(angle) * (55 + this.decision.pressure * 28), y: center.y + Math.sin(angle) * 42 }; const joints: Joint[] = [center, { x: center.x + Math.cos(angle) * 28, y: center.y + Math.sin(angle) * 28 }, target]; const solved = solveFabrik(joints, [34, 38], target, 4); this.gfx.beginPath().moveTo(solved[0].x, solved[0].y).lineTo(solved[1].x, solved[1].y).lineTo(solved[2].x, solved[2].y).strokePath(); } }
}
