export type WorldOperationKind = 'VOXEL' | 'BODY' | 'PORTAL' | 'ARCADE';
export interface LogicalClock { counter: number; actor: string; }
export interface WorldOperation { version: 1; kind: WorldOperationKind; key: string; clock: LogicalClock; values: number[]; removed: boolean; publicKey: string; signature: string; }
export interface WorldValue { kind: WorldOperationKind; key: string; clock: LogicalClock; values: number[]; removed: boolean; }

export class WorldCrdt {
  readonly maximumEntries: number; private readonly state = new Map<string, WorldValue>(); private readonly actorEntries = new Map<string, number>();
  constructor(maximumEntries = 1_000_000) { this.maximumEntries = Math.max(1, Math.min(1_000_000, Math.floor(maximumEntries))); }
  async merge(operations: readonly WorldOperation[]) { if (operations.length > 4096) throw new Error('CRDT merge batch exceeds 4,096 operations'); const verified = await Promise.all(operations.map(async operation => await verifyWorldOperation(operation) ? operation : undefined)); let accepted = 0; for (const operation of verified) if (operation && this.applyVerified(operation)) accepted++; return accepted; }
  applyVerified(operation: WorldOperation) { validateOperation(operation); const current = this.state.get(operation.key); if (current && compareClock(operation.clock, current.clock) <= 0) return false; if (!current) { if (this.state.size >= this.maximumEntries) throw new Error('CRDT world capacity reached'); const used = this.actorEntries.get(operation.clock.actor) ?? 0; if (used >= 250_000) throw new Error('CRDT actor quota reached'); this.actorEntries.set(operation.clock.actor, used + 1); } this.state.set(operation.key, { kind: operation.kind, key: operation.key, clock: { ...operation.clock }, values: [...operation.values], removed: operation.removed }); return true; }
  mergeTrusted(operations: readonly WorldOperation[]) { let accepted = 0; for (const operation of operations) if (this.applyVerified(operation)) accepted++; return accepted; }
  get(key: string) { const value = this.state.get(key); return value && !value.removed ? structuredClone(value) : undefined; }
  values(kind?: WorldOperationKind) { return [...this.state.values()].filter(value => !value.removed && (!kind || value.kind === kind)).sort((a, b) => a.key.localeCompare(b.key)).map(value => structuredClone(value)); }
  snapshot() { return [...this.state.values()].sort((a, b) => a.key.localeCompare(b.key)).map(value => structuredClone(value)); }
  restoreTrusted(values: readonly WorldValue[]) { return this.mergeTrusted(values.map(value => makeTrustedOperation(value.kind, value.key, value.clock.counter, value.clock.actor, [...value.values], value.removed))); }
  size() { return this.state.size; }
  digest() { let hash = 2166136261; for (const value of [...this.state.values()].sort((a, b) => a.key.localeCompare(b.key))) { const text = `${value.kind}|${value.key}|${value.clock.counter}|${value.clock.actor}|${value.values.join(',')}|${Number(value.removed)}`; for (let i = 0; i < text.length; i++) hash = Math.imul(hash ^ text.charCodeAt(i), 16777619); } return (hash >>> 0).toString(16).padStart(8, '0'); }
}

export async function createWorldIdentity() { const keys = await crypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify']) as CryptoKeyPair, raw = new Uint8Array(await crypto.subtle.exportKey('raw', keys.publicKey)), publicKey = base64(raw), actor = (await sha256(raw)).slice(0, 24); return { keys, publicKey, actor }; }
export async function signWorldOperation(input: Omit<WorldOperation, 'version' | 'publicKey' | 'signature'>, identity: Awaited<ReturnType<typeof createWorldIdentity>>): Promise<WorldOperation> { if (input.clock.actor !== identity.actor) throw new Error('Operation actor does not match signing identity'); const unsigned = { version: 1 as const, ...input, publicKey: identity.publicKey }; validateOperation({ ...unsigned, signature: 'pending' }); const signature = base64(new Uint8Array(await crypto.subtle.sign({ name: 'Ed25519' }, identity.keys.privateKey, new TextEncoder().encode(canonical(unsigned))))); return { ...unsigned, signature }; }
export async function verifyWorldOperation(operation: unknown): Promise<boolean> { try { validateOperation(operation as WorldOperation); const value = operation as WorldOperation, raw = fromBase64(value.publicKey); if ((await sha256(raw)).slice(0, 24) !== value.clock.actor) return false; const key = await crypto.subtle.importKey('raw', raw, { name: 'Ed25519' }, false, ['verify']); const { signature, ...unsigned } = value; return crypto.subtle.verify({ name: 'Ed25519' }, key, fromBase64(signature), new TextEncoder().encode(canonical(unsigned))); } catch { return false; } }
export function makeTrustedOperation(kind: WorldOperationKind, key: string, counter: number, actor: string, values: number[], removed = false): WorldOperation { return { version: 1, kind, key, clock: { counter, actor }, values, removed, publicKey: 'trusted-benchmark', signature: 'trusted-benchmark' }; }

function validateOperation(value: WorldOperation) { if (!value || value.version !== 1 || !['VOXEL','BODY','PORTAL','ARCADE'].includes(value.kind) || !/^[A-Za-z0-9:_,-]{1,96}$/.test(value.key) || !Number.isSafeInteger(value.clock?.counter) || value.clock.counter < 0 || !/^[a-f0-9]{8,32}$/.test(value.clock.actor) || !Array.isArray(value.values) || value.values.length > 16 || value.values.some(number => !Number.isFinite(number) || Math.abs(number) > 1_000_000) || typeof value.removed !== 'boolean' || typeof value.publicKey !== 'string' || value.publicKey.length > 256 || typeof value.signature !== 'string' || value.signature.length > 256) throw new Error('Invalid CRDT operation'); const expected = { VOXEL: 4, BODY: 7, PORTAL: 12, ARCADE: 4 }[value.kind]; if (!value.removed && value.values.length !== expected) throw new Error('Invalid CRDT value shape'); }
function compareClock(a: LogicalClock, b: LogicalClock) { return a.counter - b.counter || a.actor.localeCompare(b.actor); }
function canonical(value: Omit<WorldOperation, 'signature'>) { return JSON.stringify({ clock: { actor: value.clock.actor, counter: value.clock.counter }, key: value.key, kind: value.kind, publicKey: value.publicKey, removed: value.removed, values: value.values, version: 1 }); }
async function sha256(bytes: Uint8Array) { const copy = new Uint8Array(bytes); return [...new Uint8Array(await crypto.subtle.digest('SHA-256', copy.buffer))].map(byte => byte.toString(16).padStart(2, '0')).join(''); }
function base64(bytes: Uint8Array) { let value = ''; for (const byte of bytes) value += String.fromCharCode(byte); return btoa(value); } function fromBase64(value: string) { const binary = atob(value); return Uint8Array.from(binary, character => character.charCodeAt(0)); }
