export const SPEED_OF_LIGHT = 299_792_458;
export const GRAVITATIONAL_CONSTANT = 6.67430e-11;
export interface RelativisticState { x: number; y: number; vx: number; vy: number; coordinateTime: number; properTime: number; frequencyShift: number; }
export interface CombatInput { thrust: number; turn: number; }

export function lorentzFactor(speed: number, lightSpeed = SPEED_OF_LIGHT): number { const beta = boundedBeta(speed, lightSpeed); return 1 / Math.sqrt(1 - beta * beta); }
export function lorentzContraction(restLength: number, speed: number, lightSpeed = SPEED_OF_LIGHT): number { if (!Number.isFinite(restLength) || restLength < 0) throw new Error('Invalid rest length'); return restLength / lorentzFactor(speed, lightSpeed); }
export function longitudinalDoppler(speed: number, approaching: boolean, lightSpeed = SPEED_OF_LIGHT): number { const beta = boundedBeta(speed, lightSpeed), ratio = approaching ? (1 + beta) / (1 - beta) : (1 - beta) / (1 + beta); return Math.sqrt(ratio); }
export function schwarzschildRadius(massKilograms: number): number { if (!Number.isFinite(massKilograms) || massKilograms <= 0) throw new Error('Invalid gravitational mass'); return 2 * GRAVITATIONAL_CONSTANT * massKilograms / (SPEED_OF_LIGHT * SPEED_OF_LIGHT); }
export function gravitationalTimeFactor(massKilograms: number, radiusMeters: number): number { const horizon = schwarzschildRadius(massKilograms); if (!Number.isFinite(radiusMeters) || radiusMeters <= horizon) return 0; return Math.sqrt(1 - horizon / radiusMeters); }
export function properTimeDelta(coordinateDelta: number, speed: number, massKilograms: number, radiusMeters: number, lightSpeed = SPEED_OF_LIGHT): number { if (!Number.isFinite(coordinateDelta) || coordinateDelta < 0) throw new Error('Invalid coordinate time'); const velocityFactor = 1 / lorentzFactor(speed, lightSpeed); return coordinateDelta * velocityFactor * gravitationalTimeFactor(massKilograms, radiusMeters); }
export function weakFieldLightDeflection(massKilograms: number, impactParameterMeters: number): number { if (!Number.isFinite(impactParameterMeters) || impactParameterMeters <= schwarzschildRadius(massKilograms)) throw new Error('Impact parameter must remain outside the event horizon'); return 4 * GRAVITATIONAL_CONSTANT * massKilograms / (impactParameterMeters * SPEED_OF_LIGHT * SPEED_OF_LIGHT); }

export function stepRelativisticCombat(state: RelativisticState, input: CombatInput, deltaSeconds: number, blackHole: { x: number; y: number; mass: number }, gameLightSpeed = 1000): RelativisticState { const dt = Math.max(0, Math.min(.05, Number.isFinite(deltaSeconds) ? deltaSeconds : 0)), distanceX = blackHole.x - state.x, distanceY = blackHole.y - state.y, radius = Math.max(1, Math.hypot(distanceX, distanceY)), heading = Math.atan2(state.vy, state.vx) + Math.max(-1, Math.min(1, input.turn)) * dt * 2.2, thrust = Math.max(-1, Math.min(1, input.thrust)) * 180, gravity = Math.min(220, blackHole.mass / (radius * radius)), vx = state.vx + Math.cos(heading) * thrust * dt + distanceX / radius * gravity * dt, vy = state.vy + Math.sin(heading) * thrust * dt + distanceY / radius * gravity * dt, nextSpeed = Math.hypot(vx, vy), maximum = gameLightSpeed * .95, scale = nextSpeed > maximum ? maximum / nextSpeed : 1, limitedVx = vx * scale, limitedVy = vy * scale, limitedSpeed = Math.hypot(limitedVx, limitedVy), horizon = Math.max(.1, blackHole.mass / 50), gravityFactor = radius <= horizon ? 0 : Math.sqrt(Math.max(0, 1 - horizon / radius)), properDelta = dt / lorentzFactor(limitedSpeed, gameLightSpeed) * gravityFactor; return { x: state.x + limitedVx * dt, y: state.y + limitedVy * dt, vx: limitedVx, vy: limitedVy, coordinateTime: state.coordinateTime + dt, properTime: state.properTime + properDelta, frequencyShift: longitudinalDoppler(limitedSpeed, true, gameLightSpeed) }; }
function boundedBeta(speed: number, lightSpeed: number) { if (!Number.isFinite(speed) || !Number.isFinite(lightSpeed) || lightSpeed <= 0) throw new Error('Invalid relativistic speed'); return Math.min(.999999, Math.abs(speed) / lightSpeed); }
