import { proceduralImpulse, spatialSample } from '../../audio/spatial/SpatialDsp';
interface VoiceNode { source: MediaStreamAudioSourceNode; panner: PannerNode; filter: BiquadFilterNode; gain: GainNode; wet: GainNode; x: number; y: number; }
export class SpatialVoiceMixer {
  private context?: AudioContext; private output?: GainNode; private convolver?: ConvolverNode; private readonly voices = new Map<string, VoiceNode>();
  add(id: string, stream: MediaStream) { if (!/^[a-z0-9-]{1,48}$/.test(id) || this.voices.has(id) || this.voices.size >= 8) return false; const context = this.ensureContext(); if (!context || !this.output || !this.convolver) return false; const source = context.createMediaStreamSource(stream), panner = context.createPanner(), filter = context.createBiquadFilter(), gain = context.createGain(), wet = context.createGain(); panner.panningModel = 'HRTF'; panner.distanceModel = 'inverse'; panner.refDistance = 48; panner.maxDistance = 900; filter.type = 'lowpass'; source.connect(panner); panner.connect(filter); filter.connect(gain); gain.connect(this.output); filter.connect(wet); wet.connect(this.convolver); this.voices.set(id, { source, panner, filter, gain, wet, x: 320, y: 240 }); return true; }
  setPosition(id: string, x: number, y: number) { const voice = this.voices.get(id); if (voice && Number.isFinite(x) && Number.isFinite(y)) { voice.x = x; voice.y = y; } }
  update(listenerX: number, listenerY: number, heading: number) { const context = this.context; if (!context) return; for (const voice of this.voices.values()) { const sample = spatialSample(listenerX, listenerY, heading, voice.x, voice.y), now = context.currentTime; voice.panner.positionX.setTargetAtTime(voice.x - listenerX, now, .03); voice.panner.positionZ.setTargetAtTime(voice.y - listenerY, now, .03); voice.gain.gain.setTargetAtTime(sample.gain, now, .04); voice.filter.frequency.setTargetAtTime(sample.cutoffHz, now, .04); voice.wet.gain.setTargetAtTime(sample.reverb, now, .08); } }
  remove(id: string) { const voice = this.voices.get(id); if (!voice) return; voice.source.disconnect(); voice.panner.disconnect(); voice.filter.disconnect(); voice.gain.disconnect(); voice.wet.disconnect(); this.voices.delete(id); }
  destroy() { for (const id of [...this.voices.keys()]) this.remove(id); void this.context?.close(); this.context = undefined; }
  private ensureContext() { if (this.context) return this.context; const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioContextClass) return; const context = new AudioContextClass(), output = context.createGain(), convolver = context.createConvolver(); output.gain.value = .72; output.connect(context.destination); const impulse = context.createBuffer(2, Math.floor(context.sampleRate * .7), context.sampleRate), data = proceduralImpulse(context.sampleRate); impulse.copyToChannel(data, 0); impulse.copyToChannel(data, 1); convolver.buffer = impulse; convolver.connect(output); this.context = context; this.output = output; this.convolver = convolver; return context; }
}
