import { type LamportPublicIdentity, type LamportStateProof, LamportStateSigner, stateAttestationBytes } from '../../engine/crypto/LamportStateSignature';

export type ConsensusRecordKind = 'VOXEL_EDIT' | 'JIT_MOD' | 'BROADCAST_SEGMENT';
export interface ConsensusIdentity { actor: string; publicKey: string; keys: CryptoKeyPair; }
export interface StateProposal { version: 1; sequence: number; previousRoot: string; kind: ConsensusRecordKind; key: string; payload: string; payloadHash: string; author: string; authorKey: string; signature: string; }
export interface StateVote { proposalHash: string; actor: string; publicKey: string; signature: string; }
export interface ConsensusRecord { proposal: StateProposal; proposalHash: string; root: string; votes: StateVote[]; }
export interface StateProof { root: string; length: number; lastProposalHash: string; votes: StateVote[]; }

export class QuorumWorldLedger {
  private readonly members = new Map<string, string>(); private readonly records: ConsensusRecord[] = []; private root = '0'.repeat(64);
  constructor(identities: readonly Pick<ConsensusIdentity, 'actor' | 'publicKey'>[]) { if (identities.length < 4 || identities.length > 16) throw new Error('Consensus membership requires 4 to 16 peers'); for (const identity of identities) { if (this.members.has(identity.actor)) throw new Error('Duplicate consensus actor'); this.members.set(identity.actor, identity.publicKey); } }
  quorum(): number { return Math.floor(this.members.size * 2 / 3) + 1; }
  currentRoot(): string { return this.root; }
  length(): number { return this.records.length; }
  async propose(kind: ConsensusRecordKind, key: string, payload: Uint8Array, identity: ConsensusIdentity): Promise<StateProposal> {
    if (this.members.get(identity.actor) !== identity.publicKey) throw new Error('Proposal author is not a ledger member'); if (!/^[A-Za-z0-9:_,-]{1,96}$/.test(key) || payload.byteLength > 65_536) throw new Error('Consensus payload is outside the safe range');
    const unsigned = { version: 1 as const, sequence: this.records.length + 1, previousRoot: this.root, kind, key, payload: base64(payload), payloadHash: await sha256(payload), author: identity.actor, authorKey: identity.publicKey };
    const signature = await sign(identity.keys.privateKey, canonicalProposal(unsigned)); return { ...unsigned, signature };
  }
  async vote(proposal: StateProposal, identity: ConsensusIdentity): Promise<StateVote> { if (this.members.get(identity.actor) !== identity.publicKey) throw new Error('Voter is not a ledger member'); await this.verifyProposal(proposal); const proposalHash = await hashProposal(proposal); return { proposalHash, actor: identity.actor, publicKey: identity.publicKey, signature: await sign(identity.keys.privateKey, proposalHash) }; }
  async commit(proposal: StateProposal, votes: readonly StateVote[]): Promise<ConsensusRecord> {
    await this.verifyProposal(proposal); if (proposal.sequence !== this.records.length + 1 || proposal.previousRoot !== this.root) throw new Error('Proposal does not extend the current state root'); const proposalHash = await hashProposal(proposal), accepted = new Map<string, StateVote>();
    for (const vote of votes) { if (accepted.has(vote.actor) || vote.proposalHash !== proposalHash || this.members.get(vote.actor) !== vote.publicKey) continue; if (await verify(vote.publicKey, vote.signature, proposalHash)) accepted.set(vote.actor, structuredClone(vote)); }
    if (accepted.size < this.quorum()) throw new Error('Consensus quorum is not satisfied'); const root = await sha256(new TextEncoder().encode(`${this.root}|${proposal.sequence}|${proposalHash}`)), record = { proposal: structuredClone(proposal), proposalHash, root, votes: [...accepted.values()].sort((a, b) => a.actor.localeCompare(b.actor)) }; this.records.push(record); this.root = root; return structuredClone(record);
  }
  proof(): StateProof { const last = this.records.at(-1); return { root: this.root, length: this.records.length, lastProposalHash: last?.proposalHash ?? '0'.repeat(64), votes: structuredClone(last?.votes ?? []) }; }
  async attestPostQuantum(signer: LamportStateSigner): Promise<{ identity: LamportPublicIdentity; proof: LamportStateProof }> { const identity = signer.identity(), proof = await signer.sign(stateAttestationBytes(this.root, this.records.length)); return { identity, proof }; }
  snapshot(): ConsensusRecord[] { return structuredClone(this.records); }
  async verifyChain(records: readonly ConsensusRecord[] = this.records): Promise<boolean> { let root = '0'.repeat(64); for (let index = 0; index < records.length; index++) { const record = records[index] as ConsensusRecord; if (record.proposal.sequence !== index + 1 || record.proposal.previousRoot !== root) return false; try { await this.verifyProposal(record.proposal); } catch { return false; } const hash = await hashProposal(record.proposal); if (hash !== record.proposalHash) return false; const valid = new Set<string>(); for (const vote of record.votes) if (!valid.has(vote.actor) && vote.proposalHash === hash && this.members.get(vote.actor) === vote.publicKey && await verify(vote.publicKey, vote.signature, hash)) valid.add(vote.actor); if (valid.size < this.quorum()) return false; root = await sha256(new TextEncoder().encode(`${root}|${index + 1}|${hash}`)); if (root !== record.root) return false; } return root === (records.length ? (records.at(-1) as ConsensusRecord).root : '0'.repeat(64)); }
  private async verifyProposal(proposal: StateProposal): Promise<void> { if (!proposal || proposal.version !== 1 || !['VOXEL_EDIT', 'JIT_MOD', 'BROADCAST_SEGMENT'].includes(proposal.kind) || !Number.isSafeInteger(proposal.sequence) || proposal.sequence < 1 || !/^[a-f0-9]{64}$/.test(proposal.previousRoot) || !/^[A-Za-z0-9:_,-]{1,96}$/.test(proposal.key) || !/^[a-f0-9]{64}$/.test(proposal.payloadHash) || this.members.get(proposal.author) !== proposal.authorKey) throw new Error('Invalid state proposal'); const payload = fromBase64(proposal.payload); if (payload.byteLength > 65_536 || await sha256(payload) !== proposal.payloadHash || !await verify(proposal.authorKey, proposal.signature, canonicalProposal(proposal))) throw new Error('State proposal authentication failed'); }
}

export async function createConsensusIdentity(): Promise<ConsensusIdentity> { const keys = await crypto.subtle.generateKey({ name: 'Ed25519' }, true, ['sign', 'verify']) as CryptoKeyPair, raw = new Uint8Array(await crypto.subtle.exportKey('raw', keys.publicKey)), publicKey = base64(raw), actor = (await sha256(raw)).slice(0, 24); return { actor, publicKey, keys }; }
async function hashProposal(proposal: StateProposal) { return sha256(new TextEncoder().encode(canonicalProposal(proposal))); }
function canonicalProposal(value: Omit<StateProposal, 'signature'> | StateProposal) { return JSON.stringify({ author: value.author, authorKey: value.authorKey, key: value.key, kind: value.kind, payload: value.payload, payloadHash: value.payloadHash, previousRoot: value.previousRoot, sequence: value.sequence, version: 1 }); }
async function sign(key: CryptoKey, text: string) { return base64(new Uint8Array(await crypto.subtle.sign({ name: 'Ed25519' }, key, new TextEncoder().encode(text)))); }
async function verify(publicKey: string, signature: string, text: string) { try { const raw = fromBase64(publicKey), key = await crypto.subtle.importKey('raw', raw, { name: 'Ed25519' }, false, ['verify']); return crypto.subtle.verify({ name: 'Ed25519' }, key, fromBase64(signature), new TextEncoder().encode(text)); } catch { return false; } }
async function sha256(bytes: Uint8Array) { const copy = new Uint8Array(bytes); return [...new Uint8Array(await crypto.subtle.digest('SHA-256', copy.buffer))].map(value => value.toString(16).padStart(2, '0')).join(''); }
function base64(bytes: Uint8Array) { let text = ''; for (const byte of bytes) text += String.fromCharCode(byte); return btoa(text); } function fromBase64(text: string) { const binary = atob(text); return Uint8Array.from(binary, value => value.charCodeAt(0)); }
