import { describe, expect, it } from 'vitest';
import { createConsensusIdentity, QuorumWorldLedger } from './QuorumWorldLedger';

async function setup() { const identities = await Promise.all(Array.from({ length: 4 }, () => createConsensusIdentity())); return { identities, ledger: new QuorumWorldLedger(identities) }; }
describe('authenticated quorum world ledger', () => {
  it('commits an authenticated state root after a supermajority vote', async () => { const { identities, ledger } = await setup(), proposal = await ledger.propose('VOXEL_EDIT', 'voxel:1,2,3', new Uint8Array([1, 2, 3]), identities[0]); const votes = await Promise.all(identities.slice(0, 3).map(identity => ledger.vote(proposal, identity))); const record = await ledger.commit(proposal, votes); expect(ledger.quorum()).toBe(3); expect(record.root).toMatch(/^[a-f0-9]{64}$/); expect(await ledger.verifyChain()).toBe(true); });
  it('rejects minority votes and tampered payloads', async () => { const { identities, ledger } = await setup(), proposal = await ledger.propose('JIT_MOD', 'mod:safe', new TextEncoder().encode('input;return'), identities[0]), votes = await Promise.all(identities.slice(0, 2).map(identity => ledger.vote(proposal, identity))); await expect(ledger.commit(proposal, votes)).rejects.toThrow('quorum'); const tampered = { ...proposal, payload: btoa('different') }; await expect(ledger.vote(tampered, identities[2])).rejects.toThrow('authentication'); });
  it('rejects stale forks after the root advances', async () => { const { identities, ledger } = await setup(), first = await ledger.propose('BROADCAST_SEGMENT', 'stream:0', new Uint8Array([7]), identities[0]), stale = await ledger.propose('VOXEL_EDIT', 'voxel:stale', new Uint8Array([8]), identities[1]), votes = await Promise.all(identities.slice(0, 3).map(identity => ledger.vote(first, identity))); await ledger.commit(first, votes); const staleVotes = await Promise.all(identities.slice(0, 3).map(identity => ledger.vote(stale, identity))); await expect(ledger.commit(stale, staleVotes)).rejects.toThrow('current state root'); });
  it('authenticates quorum agreement without claiming payload truth', async () => { const { identities, ledger } = await setup(), claim = new TextEncoder().encode('mineral=999999'), proposal = await ledger.propose('VOXEL_EDIT', 'voxel:claim', claim, identities[0]), votes = await Promise.all(identities.slice(0, 3).map(identity => ledger.vote(proposal, identity))); await ledger.commit(proposal, votes); expect(await ledger.verifyChain()).toBe(true); expect(new TextDecoder().decode(Uint8Array.from(atob(ledger.snapshot()[0].proposal.payload), value => value.charCodeAt(0)))).toBe('mineral=999999'); });
});
