import Phaser from 'phaser';
import { AudioEngine } from '../../engine/AudioEngine';
import { InputManager } from '../../engine/InputManager';
import { createCloth, type SoftBodySolver } from '../../engine/physics/SoftBodySolver';
import { WebXrSessionController } from '../../engine/xr/WebXrSession';
import { eyeView, perspective, planStereoViews } from '../../engine/xr/StereoViewPlanner';
import { MotionDatabase } from '../../graphics/motion/MotionDatabase';
import { NeuralMotionMatcher } from '../../graphics/motion/NeuralMotionMatcher';
import { CrdtTransportBridge } from '../../net/crdt/CrdtTransport';
import { WorldCrdt, createWorldIdentity, makeTrustedOperation, signWorldOperation, type WorldValue } from '../../net/crdt/WorldCrdt';
import type { UnifiedTransport } from '../../net/transport/UnifiedTransport';
import { SpatialVoiceMixer } from '../../net/voice/SpatialVoiceMixer';
import { mountGameScene } from '../../ui/menu/SceneLifecycle';
import { generateNexusCabinets, nearestCabinet, type NexusCabinet } from './NexusSystems';

const ACTOR = '6e657875736c6f63', SAVE_KEY = 'neon_nexus_world_v1';
export default class NeonNexusScene extends Phaser.Scene {
  private gfx!: Phaser.GameObjects.Graphics; private hud!: Phaser.GameObjects.Text; private x = 0; private z = 0; private angle = 0; private phase = 0; private counter = 0;
  private readonly world = new WorldCrdt(4096); private cabinets: NexusCabinet[] = []; private readonly motion = new NeuralMotionMatcher(new MotionDatabase(4096)); private cloth!: SoftBodySolver; private readonly xr = new WebXrSessionController(); private readonly voice = new SpatialVoiceMixer(); private readonly identity = createWorldIdentity(); private bridge?: CrdtTransportBridge; private lastMotion = 0;
  constructor() { super('NexusScene'); }
  create() { this.x = 0; this.z = 0; this.angle = 0; this.phase = 0; this.cabinets = generateNexusCabinets(); this.cloth = createCloth(12, 6, 5); this.restore(); this.gfx = this.add.graphics(); this.hud = this.add.text(10, 8, '', { fontFamily: 'Courier', fontSize: '12px', color: '#ffffff' }).setDepth(4); this.add.text(320, 24, 'NEON NEXUS // PERSISTENT ARCADE WORLD', { fontFamily: 'Courier', fontSize: '18px', color: '#00ffcc', fontStyle: 'bold' }).setOrigin(.5).setDepth(4); this.add.text(320, 463, 'MOVE WASD  CARVE SPACE  ENTER CABINET E  VR V  AR B  PAUSE ESC', { fontFamily: 'Courier', fontSize: '11px', color: '#91a4c4' }).setOrigin(.5).setDepth(4); this.input.keyboard?.on('keydown-SPACE', () => void this.carve()); this.input.keyboard?.on('keydown-E', () => void this.enterCabinet()); this.input.keyboard?.on('keydown-V', () => void this.xr.start('immersive-vr')); this.input.keyboard?.on('keydown-B', () => void this.xr.start('immersive-ar', 120)); this.input.keyboard?.on('keydown-ESC', () => { void this.xr.stop(); this.scene.start('LobbyScene'); }); this.events.once('shutdown', () => this.shutdown()); AudioEngine.playTrack('plaza'); }
  update(time: number, delta: number) { const dt = Math.min(delta, 50) / 1000, forward = Number(InputManager.isDown('KeyW')) - Number(InputManager.isDown('KeyS')), strafe = Number(InputManager.isDown('KeyD')) - Number(InputManager.isDown('KeyA')); const vx = (Math.cos(this.angle) * forward - Math.sin(this.angle) * strafe) * 5, vz = (Math.sin(this.angle) * forward + Math.cos(this.angle) * strafe) * 5; this.x += vx * dt; this.z += vz * dt; this.phase = (this.phase + Math.hypot(vx, vz) * dt * .18) % 1; const selected = this.motion.match({ velocityX: vx, velocityZ: vz, turn: 0, slopeX: Math.sin(this.x * .1) * .2, slopeZ: Math.cos(this.z * .1) * .2, intentX: strafe, intentZ: forward, phase: this.phase }, dt); this.lastMotion = selected.index; this.cloth.step(dt, 130, 3); this.voice.update(this.x, this.z, this.angle); this.draw(time, selected.pose); }
  attachVoice(id: string, stream: MediaStream, x = 0, z = 0) { const added = this.voice.add(id, stream); if (added) this.voice.setPosition(id, x, z); return added; }
  attachWorldTransport(transport: UnifiedTransport) { this.bridge?.close(); this.bridge = new CrdtTransportBridge(transport, this.world); }
  shutdown() { void this.xr.stop(); this.bridge?.close(); this.bridge = undefined; this.voice.destroy(); }
  private async carve() { this.counter++; const identity = await this.identity, operation = await signWorldOperation({ kind: 'VOXEL', key: `crater:${this.counter}`, clock: { counter: this.counter, actor: identity.actor }, values: [this.x, this.z, 3, 8], removed: false }, identity); await this.world.merge([operation]); await this.bridge?.broadcast([operation]); this.save(); AudioEngine.playEffect('EXPLOSION'); }
  private async enterCabinet() { const cabinet = nearestCabinet(this.cabinets, this.x, this.z); if (!cabinet || Math.hypot(cabinet.x - this.x, cabinet.z - this.z) > 4) return; await mountGameScene({ has: key => Boolean(this.scene.manager.keys[key]), add: (key, SceneClass) => this.scene.add(key, SceneClass, false), start: (key, data) => this.scene.start(key, data) }, cabinet.scene, { difficulty: 'NORMAL', mode: 'SOLO' }); }
  private restore() { try { const values = JSON.parse(localStorage.getItem(SAVE_KEY) ?? '[]') as WorldValue[]; if (!Array.isArray(values) || values.length > 4096) return; this.world.restoreTrusted(values); this.counter = values.reduce((highest, value) => Math.max(highest, value.clock.counter), 0); } catch { localStorage.removeItem(SAVE_KEY); } }
  private save() { localStorage.setItem(SAVE_KEY, JSON.stringify(this.world.snapshot())); }
  private draw(time: number, pose: Float32Array) { const g = this.gfx.clear(); g.fillGradientStyle(0x01030d, 0x01030d, 0x111042, 0x111042).fillRect(0, 0, 640, 480); const horizon = 220; for (let depth = 1; depth <= 12; depth++) { const y = horizon + 220 / depth; g.lineStyle(1, depth % 2 ? 0x00bbff : 0xaa22ff, .16).lineBetween(0, y, 640, y); } for (let line = -12; line <= 12; line++) g.lineStyle(1, 0x006688, .18).lineBetween(320, horizon, 320 + line * 50, 445); for (const cabinet of this.cabinets) { const dx = cabinet.x - this.x, dz = cabinet.z - this.z, distance = Math.max(1, Math.hypot(dx, dz)), relative = wrap(Math.atan2(dz, dx) - this.angle); if (Math.abs(relative) > 1.25) continue; const px = 320 + Math.tan(relative) * 245, height = 155 / distance; g.fillStyle(Phaser.Display.Color.HSLToColor(cabinet.hue / 360, .9, .55).color, .85).fillRect(px - height * .3, horizon - height, height * .6, height); g.lineStyle(1, 0xffffff, .7).strokeRect(px - height * .22, horizon - height * .82, height * .44, height * .38); } for (let i = 0; i < this.cloth.x.length; i++) g.fillStyle(0xff33aa, .3).fillCircle(500 + this.cloth.x[i] * .24, 50 + this.cloth.y[i] * .24, 1); const bob = pose[0] * 14; g.fillStyle(0x00ffcc, .9).fillCircle(320, 357 + bob, 8).lineStyle(3, 0x00ffcc, .8).lineBetween(320, 365 + bob, 320 + pose[2] * 50, 392 + bob).lineBetween(320, 365 + bob, 320 + pose[3] * 50, 392 + bob); const nearest = nearestCabinet(this.cabinets, this.x, this.z); this.hud.setText(`WORLD ${this.world.digest()}  OPS ${this.world.size()}  MOTION ${this.lastMotion}/4096  XR ${this.xr.active() ? 'ACTIVE' : 'DESKTOP'}  NEAREST ${nearest.scene.replace('Scene', '').toUpperCase()}  ${(Math.sin(time * .002) * .5 + .5).toFixed(2)}`); }
  nexusDiagnostics() { const projection = perspective(Math.PI / 2, 1, .1, 100), views = [{ eye: 'left' as const, projection, view: eyeView(-.032) }, { eye: 'right' as const, projection, view: eyeView(.032) }], stereo = planStereoViews(views, 1); const matcher = new NeuralMotionMatcher(new MotionDatabase(512, 4), 5), match = matcher.match({ velocityX: 2, velocityZ: 0, turn: 0, slopeX: .1, slopeZ: 0, intentX: 1, intentZ: 0, phase: .2 }); const a = new WorldCrdt(), b = new WorldCrdt(), operations = [makeTrustedOperation('VOXEL', 'diag:1', 1, ACTOR, [0, 0, 2, 4]), makeTrustedOperation('ARCADE', 'diag:2', 2, ACTOR, [1, 2, 3, 4])]; a.mergeTrusted(operations); b.mergeTrusted([...operations].reverse()); return { stereoViews: stereo.length, eyesDistinct: stereo[0].projectionView.some((value, index) => value !== stereo[1].projectionView[index]), motionIndex: match.index, motionPose: [...match.pose.slice(0, 3)], crdtConverged: a.digest() === b.digest(), arcades: this.cabinets.length }; }
}
function wrap(angle: number) { while (angle > Math.PI) angle -= Math.PI * 2; while (angle < -Math.PI) angle += Math.PI * 2; return angle; }
