import type Phaser from 'phaser';
import { InputManager } from '../InputManager';
import { ReplayPlayer, ReplayRecorder, signReplay, verifyReplay, type ReplayLedger, type SignedReplay } from './ReplayEngine';
import { loadGameScene } from '../../sceneRegistry';
import type { HighScoreProof } from '../../core/crypto/HighScoreProof';

export class ReplayRuntime {
  private recorder?: ReplayRecorder; private scene = ''; private player?: ReplayPlayer; private loadedLedger?: ReplayLedger; private root?: HTMLElement; private frame = 0; private readonly game: Phaser.Game;
  constructor(game: Phaser.Game) { this.game = game; this.installHud(); window.addEventListener('keydown', event => { if (event.code === 'KeyR' && !(event.target as HTMLElement | null)?.matches('input,textarea')) this.toggleHud(); }); }
  sample() { const active = this.game.scene.getScenes(true).find(scene => !['LobbyScene','PauseScene','SettingsScene','NameEntryScene','AchievementsScene'].includes(scene.scene.key)); const scene = active?.scene.key ?? ''; if (!this.player && scene !== this.scene) { if (this.recorder) void this.persist(this.recorder.finish()); this.scene = scene; this.recorder = scene ? new ReplayRecorder(scene, 0x42594f53) : undefined; this.frame = 0; } if (this.player) { const state = this.player.step(); InputManager.setReplayMask(state.mask); this.syncHud(state.tick, state.progress); if (state.progress >= 1) { this.player.pause(); this.player = undefined; InputManager.setReplayMask(null); } } else { this.recorder?.record(InputManager.getP1Mask()); this.frame++; } }
  async load(ledger: ReplayLedger) { if (!this.game.scene.keys[ledger.scene]) this.game.scene.add(ledger.scene, await loadGameScene(ledger.scene), false); this.recorder = undefined; this.scene = ledger.scene; this.loadedLedger = ledger; this.game.scene.start(ledger.scene, { seed: ledger.seed, replay: true, difficulty: 'NORMAL', mode: 'SOLO' }); this.player = new ReplayPlayer(ledger); this.player.play(); InputManager.setReplayMask(0); this.showHud(true); }
  async prove(scene: string, score: number) { if (!this.recorder || this.scene !== scene || !Number.isFinite(score)) return; const crypto = await import('../../core/crypto/HighScoreProof'); const { VerifiedScoreStore } = await import('../../core/leaderboard/VerifiedScoreStore'); const proof = await crypto.signProof(scene, Math.max(0, Math.floor(score)), crypto.compressReplay(this.recorder.finish()), await crypto.createProofIdentity()); new VerifiedScoreStore().put(proof); window.dispatchEvent(new CustomEvent('arcade-proof-ready', { detail: proof })); return proof; }
  async watchProof(proof: HighScoreProof) { const { expandReplay } = await import('../../core/crypto/HighScoreProof'); const masks = expandReplay(proof.replay); const inputs: ReplayLedger['inputs'] = []; for (let tick = 0; tick < masks.length; tick++) if (tick === 0 || masks[tick] !== masks[tick - 1]) inputs.push({ tick, mask: masks[tick] }); await this.load({ version: 1, scene: proof.game, seed: proof.replay.seed, tickRate: 60, durationTicks: proof.replay.ticks, inputs }); }
  private async persist(ledger: ReplayLedger) { const signed = await signReplay(ledger); const json = JSON.stringify(signed); if (json.length < 262144) localStorage.setItem('retro_replay_latest_v1', json); }
  private installHud() { const root = document.createElement('aside'); root.className = 'replay-hud'; root.hidden = true; root.dataset.arcadeOverlay = 'true'; root.innerHTML = '<strong>REPLAY SPECTATOR</strong><button data-play>PLAY</button><button data-pause>PAUSE</button><button data-rewind>-5S</button><button data-forward>+5S</button><input data-timeline type="range" min="0" max="1000" value="0"><output data-time>0</output><button data-close>ESC EXIT</button>'; document.body.appendChild(root); this.root = root; root.querySelector('[data-close]')?.addEventListener('click', () => this.showHud(false)); root.querySelector('[data-play]')?.addEventListener('click', () => this.player?.play()); root.querySelector('[data-pause]')?.addEventListener('click', () => this.player?.pause()); root.querySelector('[data-rewind]')?.addEventListener('click', () => this.seekRelative(-300)); root.querySelector('[data-forward]')?.addEventListener('click', () => this.seekRelative(300)); root.querySelector<HTMLInputElement>('[data-timeline]')?.addEventListener('input', event => { const target = event.target as HTMLInputElement; if (this.loadedLedger && this.player) this.player.seek(Math.floor(Number(target.value) / 1000 * this.loadedLedger.durationTicks)); }); window.addEventListener('arcade-watch-proof', event => void this.watchProof((event as CustomEvent<HighScoreProof>).detail)); window.addEventListener('keydown', event => { if (event.code === 'Escape' && !root.hidden) this.showHud(false); }); }
  private readLatest() { try { return JSON.parse(localStorage.getItem('retro_replay_latest_v1') ?? 'null') as SignedReplay | null; } catch { return null; } }
  private toggleHud() { this.showHud(Boolean(this.root?.hidden)); if (!this.player) void this.openLatest(); }
  private async openLatest() { const replay = this.readLatest(); if (!replay || !await verifyReplay(replay)) { this.root?.querySelector<HTMLOutputElement>('[data-time]')?.setAttribute('value', 'INVALID'); return; } await this.load(replay.ledger); }
  private showHud(show: boolean) { if (this.root) this.root.hidden = !show; }
  private seekRelative(delta: number) { if (!this.player) return; const state = this.player.state(); this.player.seek(state.tick + delta); }
  private syncHud(tick: number, progress: number) { const slider = this.root?.querySelector<HTMLInputElement>('[data-timeline]'); const output = this.root?.querySelector<HTMLOutputElement>('[data-time]'); if (slider) slider.value = String(Math.floor(progress * 1000)); if (output) output.value = `${(tick / 60).toFixed(1)}S`; }
}
