import type { ModAction, ModEventName, ModManifest } from '../../mods/ModSchema';

export type VisualNodeKind = 'EVENT' | 'HAZARD' | 'SCORE' | 'EFFECT' | 'PATCH';
export interface VisualNode { id: string; kind: VisualNodeKind; x: number; y: number; config: Record<string, string | number>; }
export interface VisualEdge { from: string; to: string; }
export interface VisualGraph { nodes: VisualNode[]; edges: VisualEdge[]; }

export function compileVisualGraph(graph: VisualGraph, identity: { id: string; name: string; version: string }): ModManifest {
  if (graph.nodes.length > 64 || graph.edges.length > 128) throw new Error('Visual graph exceeds node or edge limits'); const ids = new Set<string>(); for (const node of graph.nodes) { if (!/^[a-z0-9-]{3,32}$/.test(node.id) || ids.has(node.id) || !Number.isFinite(node.x) || !Number.isFinite(node.y)) throw new Error('Visual node identity is invalid'); ids.add(node.id); } for (const edge of graph.edges) if (!ids.has(edge.from) || !ids.has(edge.to) || edge.from === edge.to) throw new Error('Visual edge is invalid'); rejectCycles(graph);
  const hazards: ModManifest['stage']['hazards'] = []; const hooks: ModManifest['hooks'] = [];
  for (const eventNode of graph.nodes.filter(node => node.kind === 'EVENT')) { const event = String(eventNode.config.event) as ModEventName; if (!['SPAWN','COLLISION','SCORE_UPDATE','STAGE_CLEAR','BOSS_ENTRY','POWER_UP'].includes(event)) throw new Error('Visual event is invalid'); const actions: ModAction[] = []; for (const node of reachableActions(graph, eventNode.id)) { if (node.kind === 'HAZARD') { const hazard = hazardFrom(node); hazards.push(hazard); actions.push({ type: 'SPAWN_HAZARD', kind: hazard.kind, lane: hazard.lane }); } else if (node.kind === 'SCORE') actions.push({ type: 'SCALE_SCORE', factor: bounded(node.config.factor, 0.5, 3, 'score factor') }); else if (node.kind === 'EFFECT') { const effect = String(node.config.effect) as 'LASER' | 'EXPLOSION' | 'COIN' | 'POWER_UP' | 'STAGE_CLEAR'; if (!['LASER','EXPLOSION','COIN','POWER_UP','STAGE_CLEAR'].includes(effect)) throw new Error('Visual effect is invalid'); actions.push({ type: 'PLAY_EFFECT', effect }); } else if (node.kind === 'PATCH') { const patchId = String(node.config.patchId); if (!/^[a-z0-9-]{3,32}$/.test(patchId)) throw new Error('Visual patch id is invalid'); actions.push({ type: 'PLAY_PATCH', patchId }); } } hooks.push({ event, actions: actions.slice(0, 16) }); }
  return { apiVersion: 1, id: identity.id, name: identity.name, version: identity.version, stage: { hazards: uniqueHazards(hazards).slice(0, 64) }, hooks: hooks.slice(0, 16) };
}
function reachableActions(graph: VisualGraph, start: string) { const outgoing = new Map<string, string[]>(); for (const edge of graph.edges) outgoing.set(edge.from, [...(outgoing.get(edge.from) ?? []), edge.to]); const queue = [...(outgoing.get(start) ?? [])]; const visited = new Set<string>(); const nodes: VisualNode[] = []; while (queue.length) { const id = queue.shift()!; if (visited.has(id)) continue; visited.add(id); const node = graph.nodes.find(candidate => candidate.id === id); if (!node) continue; if (node.kind !== 'EVENT') nodes.push(node); queue.push(...(outgoing.get(id) ?? [])); } return nodes; }
function hazardFrom(node: VisualNode) { const kind = String(node.config.kind) as 'SPIKE' | 'DRONE' | 'WALL'; if (!['SPIKE','DRONE','WALL'].includes(kind)) throw new Error('Visual hazard kind is invalid'); return { lane: Math.trunc(bounded(node.config.lane, 0, 7, 'hazard lane')), offset: bounded(node.config.offset, 0, 1, 'hazard offset'), speed: bounded(node.config.speed, 0.1, 4, 'hazard speed'), kind }; }
function uniqueHazards(hazards: ModManifest['stage']['hazards']) { const seen = new Set<string>(); return hazards.filter(hazard => { const key = `${hazard.lane}:${hazard.offset}:${hazard.speed}:${hazard.kind}`; if (seen.has(key)) return false; seen.add(key); return true; }); }
function rejectCycles(graph: VisualGraph) { const edges = new Map<string, string[]>(); for (const edge of graph.edges) edges.set(edge.from, [...(edges.get(edge.from) ?? []), edge.to]); const active = new Set<string>(); const done = new Set<string>(); const visit = (id: string) => { if (active.has(id)) throw new Error('Visual graph contains a cycle'); if (done.has(id)) return; active.add(id); for (const next of edges.get(id) ?? []) visit(next); active.delete(id); done.add(id); }; for (const node of graph.nodes) visit(node.id); }
function bounded(value: string | number | undefined, minimum: number, maximum: number, name: string) { const number = Number(value); if (!Number.isFinite(number) || number < minimum || number > maximum) throw new Error(`${name} is outside bounds`); return number; }
