import { signModManifest } from '../../mods/crypto/SignedModPackage';
import { compileVisualGraph, type VisualGraph, type VisualNodeKind } from './VisualGraph';
import { compileGraphBytecode } from '../../engine/vm/VisualBytecodeCompiler';

export class VisualModStudio {
  private readonly root: HTMLElement; private readonly canvas: HTMLCanvasElement; private readonly context: CanvasRenderingContext2D; private graph: VisualGraph = { nodes: [], edges: [] }; private selected?: string; private dragging?: { id: string; dx: number; dy: number }; private signingKey?: CryptoKey;
  constructor() { this.root = document.createElement('aside'); this.root.className = 'visual-studio'; this.root.hidden = true; this.root.innerHTML = `<header><div><small>BIOSSYSTEM DECLARATIVE IDE</small><h2>VISUAL MOD STUDIO</h2></div><button data-close type="button">X</button></header><div class="studio-toolbar"><input data-id value="visual-stage" maxlength="32"><input data-name value="Visual Stage" maxlength="48"><button data-node="EVENT">EVENT</button><button data-node="HAZARD">HAZARD</button><button data-node="SCORE">SCORE</button><button data-node="EFFECT">SFX</button><button data-node="PATCH">PATCH</button><button data-compile>COMPILE + SIGN</button></div><canvas width="900" height="480" aria-label="Visual mod node graph"></canvas><textarea data-output readonly aria-label="Signed visual mod package"></textarea><output data-status>ADD NODES, THEN CLICK TWO NODES TO CONNECT</output>`; document.body.appendChild(this.root); this.canvas = this.root.querySelector('canvas')!; this.context = this.canvas.getContext('2d')!; this.bind(); this.draw(); }
  toggle(force?: boolean) { this.root.hidden = force === undefined ? !this.root.hidden : !force; if (!this.root.hidden) this.draw(); }
  private bind() { document.getElementById('visual-studio-toggle')?.addEventListener('click', () => this.toggle()); this.root.querySelector('[data-close]')?.addEventListener('click', () => this.toggle(false)); for (const button of this.root.querySelectorAll<HTMLButtonElement>('[data-node]')) button.addEventListener('click', () => this.addNode(button.dataset.node as VisualNodeKind)); this.root.querySelector('[data-compile]')?.addEventListener('click', () => void this.compile()); this.canvas.addEventListener('pointerdown', event => this.pointerDown(event)); this.canvas.addEventListener('pointermove', event => this.pointerMove(event)); this.canvas.addEventListener('pointerup', () => { this.dragging = undefined; }); window.addEventListener('keydown', event => { if (event.code === 'KeyV' && !(event.target as HTMLElement | null)?.matches('input, textarea, select')) this.toggle(); }); }
  private addNode(kind: VisualNodeKind) { const index = this.graph.nodes.length; const defaults: Record<VisualNodeKind, Record<string, string | number>> = { EVENT: { event: 'STAGE_CLEAR' }, HAZARD: { kind: 'DRONE', lane: 2, offset: 0.5, speed: 1.2 }, SCORE: { factor: 1.25 }, EFFECT: { effect: 'POWER_UP' }, PATCH: { patchId: 'neon-pulse' } }; this.graph.nodes.push({ id: `${kind.toLowerCase()}-${index + 1}`, kind, x: 40 + index % 5 * 165, y: 55 + Math.floor(index / 5) * 110, config: defaults[kind] }); this.draw(); }
  private pointerDown(event: PointerEvent) { const point = this.point(event); const node = [...this.graph.nodes].reverse().find(candidate => point.x >= candidate.x && point.x <= candidate.x + 135 && point.y >= candidate.y && point.y <= candidate.y + 62); if (!node) { this.selected = undefined; this.draw(); return; } if (this.selected && this.selected !== node.id) { if (!this.graph.edges.some(edge => edge.from === this.selected && edge.to === node.id)) this.graph.edges.push({ from: this.selected, to: node.id }); this.selected = undefined; } else { this.selected = node.id; this.dragging = { id: node.id, dx: point.x - node.x, dy: point.y - node.y }; } this.draw(); }
  private pointerMove(event: PointerEvent) { if (!this.dragging || !(event.buttons & 1)) return; const point = this.point(event); const node = this.graph.nodes.find(candidate => candidate.id === this.dragging!.id); if (!node) return; node.x = Math.max(0, Math.min(this.canvas.width - 135, point.x - this.dragging.dx)); node.y = Math.max(0, Math.min(this.canvas.height - 62, point.y - this.dragging.dy)); this.draw(); }
  private async compile() { try { const id = (this.root.querySelector('[data-id]') as HTMLInputElement).value; const name = (this.root.querySelector('[data-name]') as HTMLInputElement).value; const manifest = compileVisualGraph(this.graph, { id, name, version: '1.0.0' }); const bytecode = compileGraphBytecode(this.graph); const signed = await signModManifest(manifest, this.signingKey); this.signingKey = signed.privateKey; (this.root.querySelector('[data-output]') as HTMLTextAreaElement).value = JSON.stringify(signed.package, null, 2); this.status(`SIGNED ${signed.package.sha256.slice(0, 16)} // NEONVM ${bytecode.length} WORDS`); } catch (error) { this.status(error instanceof Error ? error.message : 'COMPILE FAILED'); } }
  private draw() { const context = this.context; context.fillStyle = '#02060b'; context.fillRect(0, 0, this.canvas.width, this.canvas.height); context.strokeStyle = '#123d36'; for (let x = 0; x < this.canvas.width; x += 24) for (let y = 0; y < this.canvas.height; y += 24) context.strokeRect(x, y, 1, 1); for (const edge of this.graph.edges) { const from = this.node(edge.from); const to = this.node(edge.to); if (!from || !to) continue; context.strokeStyle = '#00ffae'; context.beginPath(); context.moveTo(from.x + 135, from.y + 31); context.bezierCurveTo(from.x + 175, from.y + 31, to.x - 40, to.y + 31, to.x, to.y + 31); context.stroke(); } for (const node of this.graph.nodes) { context.fillStyle = node.id === this.selected ? '#173a36' : '#08151a'; context.strokeStyle = nodeColor(node.kind); context.lineWidth = 2; context.fillRect(node.x, node.y, 135, 62); context.strokeRect(node.x, node.y, 135, 62); context.fillStyle = '#ffffff'; context.font = 'bold 12px monospace'; context.fillText(node.kind, node.x + 9, node.y + 20); context.fillStyle = '#719d96'; context.font = '10px monospace'; context.fillText(node.id, node.x + 9, node.y + 42); } }
  private point(event: PointerEvent) { const bounds = this.canvas.getBoundingClientRect(); return { x: (event.clientX - bounds.left) * this.canvas.width / bounds.width, y: (event.clientY - bounds.top) * this.canvas.height / bounds.height }; }
  private node(id: string) { return this.graph.nodes.find(node => node.id === id); }
  private status(value: string) { const output = this.root.querySelector('output'); if (output) output.textContent = value; }
}
function nodeColor(kind: VisualNodeKind) { return ({ EVENT: '#00ffae', HAZARD: '#ff2255', SCORE: '#ffcc00', EFFECT: '#00ccff', PATCH: '#ff2ec4' } as const)[kind]; }
export function installVisualModStudio() { return new VisualModStudio(); }
