export interface LensField { width: number; height: number; uv: Float32Array<ArrayBuffer>; checksum: number; }
export function gravitationalLensUv(u: number, v: number, strength = .035, horizon = .08): { u: number; v: number; captured: boolean } { const x = u - .5, y = v - .5, radius = Math.max(1e-5, Math.hypot(x, y)), captured = radius < Math.max(.001, Math.min(.25, horizon)), bend = captured ? 0 : Math.min(.4, Math.max(0, strength) / (radius * radius)); return { u: .5 + x * (1 + bend), v: .5 + y * (1 + bend), captured }; }
export function generateLensingField(width = 256, height = 256, strength = .035): LensField { const w = Math.max(1, Math.min(1024, Math.floor(width))), h = Math.max(1, Math.min(1024, Math.floor(height))), uv = new Float32Array(w * h * 2); let checksum = 2166136261; for (let pixel = 0; pixel < w * h; pixel++) { const mapped = gravitationalLensUv((pixel % w + .5) / w, (Math.floor(pixel / w) + .5) / h, strength), offset = pixel * 2; uv[offset] = mapped.captured ? -1 : mapped.u; uv[offset + 1] = mapped.captured ? -1 : mapped.v; checksum = Math.imul(checksum ^ Math.round(uv[offset] * 65536) ^ Math.round(uv[offset + 1] * 131072), 16777619); } return { width: w, height: h, uv, checksum: checksum >>> 0 }; }
export const HORIZON_LENSING_WGSL = `
struct Params { width: u32, height: u32, strength: f32, horizon: f32 }
@group(0) @binding(0) var sourceTexture: texture_2d<f32>; @group(0) @binding(1) var outputTexture: texture_storage_2d<rgba8unorm, write>; @group(0) @binding(2) var<uniform> params: Params;
@compute @workgroup_size(8, 8) fn main(@builtin(global_invocation_id) id: vec3u) { if (id.x >= params.width || id.y >= params.height) { return; } let uv = (vec2f(id.xy) + .5) / vec2f(params.width, params.height); let delta = uv - .5; let radius = max(.00001, length(delta)); if (radius < params.horizon) { textureStore(outputTexture, vec2i(id.xy), vec4f(0.0, 0.0, 0.0, 1.0)); return; } let mapped = .5 + delta * (1.0 + min(.4, params.strength / (radius * radius))); let source = textureLoad(sourceTexture, vec2i(clamp(mapped, vec2f(0.0), vec2f(.9999)) * vec2f(params.width, params.height)), 0); let doppler = clamp(1.0 + delta.x * .35 / radius, .65, 1.35); textureStore(outputTexture, vec2i(id.xy), vec4f(source.r * doppler, source.g, source.b / doppler, 1.0)); }`;
interface Device { createShaderModule(input: { code: string }): unknown; createComputePipelineAsync(input: unknown): Promise<unknown>; }
export async function compileHorizonLensingPipeline(): Promise<'COMPILED' | 'UNAVAILABLE'> { if (typeof navigator === 'undefined') return 'UNAVAILABLE'; const gpu = (navigator as Navigator & { gpu?: { requestAdapter(): Promise<{ requestDevice(): Promise<Device> } | null> } }).gpu; if (!gpu) return 'UNAVAILABLE'; const adapter = await gpu.requestAdapter(); if (!adapter) return 'UNAVAILABLE'; const device = await adapter.requestDevice(); const module = device.createShaderModule({ code: HORIZON_LENSING_WGSL }); await device.createComputePipelineAsync({ layout: 'auto', compute: { module, entryPoint: 'main' } }); return 'COMPILED'; }
