export const TRAIT_COUNT = 8;
export interface Habitat { temperature: number; moisture: number; fluid: number; elevation: number; }
export interface GenerationResult { generation: number; population: Float32Array; bestFitness: number; meanFitness: number; diversity: number; }

export class GeneticEcosystem {
  private population: Float32Array; private generation = 0; private readonly size: number; private readonly seed: number;
  constructor(size = 256, seed = 0x47454e45) { this.size = Math.max(16, Math.min(4096, Math.floor(size))); this.seed = seed | 0; this.population = createPopulation(this.size, this.seed); }
  evolve(habitat: Habitat, mutationRate = .08) { const result = evolvePopulation(this.population, habitat, this.seed ^ this.generation, mutationRate); this.population = result.population; this.generation++; return { ...result, generation: this.generation }; }
  snapshot() { return { version: 1 as const, generation: this.generation, population: [...this.population] }; }
  restore(value: unknown) { if (!record(value) || value.version !== 1 || typeof value.generation !== 'number' || !Number.isSafeInteger(value.generation) || value.generation < 0 || !Array.isArray(value.population) || value.population.length !== this.size * TRAIT_COUNT || value.population.some(item => typeof item !== 'number' || !Number.isFinite(item) || item < 0 || item > 1)) throw new Error('Invalid ecosystem snapshot'); this.generation = value.generation; this.population = Float32Array.from(value.population as number[]); }
  getPopulation() { return this.population.slice(); }
  currentGeneration() { return this.generation; }
}

export function createPopulation(size: number, seed: number) { const count = Math.max(2, Math.min(4096, Math.floor(size))), output = new Float32Array(count * TRAIT_COUNT); let state = seed | 0; for (let index = 0; index < output.length; index++) { state = random(state); output[index] = (state >>> 0) / 4294967296; } return output; }
export function evolvePopulation(source: Float32Array, habitat: Habitat, seed: number, mutationRate = .08): Omit<GenerationResult, 'generation'> { if (source.length % TRAIT_COUNT || source.length < TRAIT_COUNT * 2 || source.length > TRAIT_COUNT * 4096) throw new Error('Invalid genetic population buffer'); const environment = normalizeHabitat(habitat), count = source.length / TRAIT_COUNT, ranked = Array.from({ length: count }, (_, index) => ({ index, fitness: genomeFitness(source.subarray(index * TRAIT_COUNT, (index + 1) * TRAIT_COUNT), environment) })).sort((a, b) => b.fitness - a.fitness || a.index - b.index), elite = Math.max(2, Math.ceil(count / 4)), output = new Float32Array(source.length); let state = seed | 0; for (let child = 0; child < count; child++) { state = random(state); const left = ranked[(state >>> 0) % elite].index; state = random(state); const right = ranked[(state >>> 0) % elite].index; for (let trait = 0; trait < TRAIT_COUNT; trait++) { state = random(state); const mix = (state >>> 0) / 4294967296, a = source[left * TRAIT_COUNT + trait], b = source[right * TRAIT_COUNT + trait]; let value = a * mix + b * (1 - mix); state = random(state); if ((state >>> 0) / 4294967296 < clamp(mutationRate, 0, .5)) { state = random(state); value += ((state >>> 0) / 4294967296 - .5) * .3; } output[child * TRAIT_COUNT + trait] = clamp(value, 0, 1); } } const fitnesses = Array.from({ length: count }, (_, index) => genomeFitness(output.subarray(index * TRAIT_COUNT, (index + 1) * TRAIT_COUNT), environment)), meanFitness = fitnesses.reduce((a, b) => a + b, 0) / count; return { population: output, bestFitness: Math.max(...fitnesses), meanFitness, diversity: populationDiversity(output) }; }
export function genomeFitness(genome: ArrayLike<number>, habitat: Habitat) { const target = normalizeHabitat(habitat), adaptation = 1 - (Math.abs(genome[0] - target.temperature) + Math.abs(genome[1] - target.moisture) + Math.abs(genome[2] - target.fluid) + Math.abs(genome[3] - target.elevation)) / 4, mobility = genome[4] * (.4 + Math.abs(target.elevation - .5)), fertility = genome[5] * target.moisture, efficiency = 1 - genome[6] * .35, cooperation = genome[7] * .15; return Math.max(0, adaptation * .62 + mobility * .12 + fertility * .12 + efficiency * .09 + cooperation); }
export function populationDiversity(population: Float32Array) { const count = population.length / TRAIT_COUNT; let total = 0; for (let trait = 0; trait < TRAIT_COUNT; trait++) { let mean = 0; for (let entity = 0; entity < count; entity++) mean += population[entity * TRAIT_COUNT + trait] / count; for (let entity = 0; entity < count; entity++) total += Math.abs(population[entity * TRAIT_COUNT + trait] - mean); } return total / population.length; }
function normalizeHabitat(value: Habitat): Habitat { return { temperature: clamp(value.temperature, 0, 1), moisture: clamp(value.moisture, 0, 1), fluid: clamp(value.fluid, 0, 1), elevation: clamp(value.elevation, 0, 1) }; }
function random(value: number) { value ^= value << 13; value ^= value >>> 17; value ^= value << 5; return value | 0; }
function clamp(value: number, low: number, high: number) { return Math.max(low, Math.min(high, Number.isFinite(value) ? value : low)); }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
