import{inputChecksum,type NetInputFrame}from'../../net/InputCodec';import type{DeterministicAdapter}from'../../net/rollback/RollbackEngine';
export type FighterAction=0|1|2|3;export interface FighterState{x:number;y:number;facing:number;health:number;action:FighterAction;actionFrame:number;hitstun:number;blockstun:number;combo:number;comboDamage:number}export interface KombatState{frame:number;roundTicks:number;p1:FighterState;p2:FighterState;winner:number}
export const MOVES={JAB:{startup:3,active:2,recovery:7,damage:60,hitstun:10,blockstun:5,reach:46},KICK:{startup:7,active:3,recovery:12,damage:100,hitstun:15,blockstun:8,reach:62}}as const;
export function initialKombatState():KombatState{return{frame:0,roundTicks:99*60,p1:fighter(170,1),p2:fighter(470,-1),winner:0};}
export function stepKombat(state:KombatState,p1Input:NetInputFrame,p2Input:NetInputFrame){const next=cloneKombatState(state);next.frame++;next.roundTicks=Math.max(0,next.roundTicks-1);tick(next.p1,p1Input,next.p2);tick(next.p2,p2Input,next.p1);strike(next.p1,next.p2,p2Input);strike(next.p2,next.p1,p1Input);separate(next.p1,next.p2);if(next.p1.health<=0||next.p2.health<=0||next.roundTicks===0)next.winner=next.p1.health===next.p2.health?3:next.p1.health>next.p2.health?1:2;return next;}
function tick(f:FighterState,input:NetInputFrame,opponent:FighterState){f.facing=f.x<=opponent.x?1:-1;if(f.hitstun>0){f.hitstun--;return;}if(f.blockstun>0){f.blockstun--;return;}if(f.action){f.actionFrame++;const move=f.action===1?MOVES.JAB:MOVES.KICK;if(f.actionFrame>=move.startup+move.active+move.recovery){f.action=0;f.actionFrame=0;}return;}f.x=clamp(f.x+Math.sign(input.axisX)*3,22,618);if(input.buttons&16){f.action=input.buttons&1?2:1;f.actionFrame=0;}}
function strike(attacker:FighterState,defender:FighterState,defenderInput:NetInputFrame){if(attacker.action!==1&&attacker.action!==2)return;const move=attacker.action===1?MOVES.JAB:MOVES.KICK;if(attacker.actionFrame<move.startup||attacker.actionFrame>=move.startup+move.active)return;if(Math.abs(defender.x-attacker.x)>move.reach)return;const blocking=Math.sign(defenderInput.axisX)===-defender.facing;if(blocking){defender.blockstun=Math.max(defender.blockstun,move.blockstun);defender.health=Math.max(0,defender.health-Math.floor(move.damage*.1));attacker.actionFrame=move.startup+move.active;return;}defender.combo=defender.hitstun>0?defender.combo+1:1;const scale=Math.max(.25,1-(defender.combo-1)*.12),damage=Math.floor(move.damage*scale);defender.health=Math.max(0,defender.health-damage);defender.comboDamage+=damage;defender.hitstun=move.hitstun;defender.x=clamp(defender.x+attacker.facing*(8+damage/20),22,618);attacker.actionFrame=move.startup+move.active;}
function separate(a:FighterState,b:FighterState){const overlap=36-Math.abs(a.x-b.x);if(overlap<=0)return;const direction=a.x<=b.x?-1:1;a.x=clamp(a.x+direction*overlap/2,22,618);b.x=clamp(b.x-direction*overlap/2,22,618);}
export function kombatHitboxes(state:KombatState){return{p1:{hurt:{x:state.p1.x-16,y:state.p1.y-64,width:32,height:64},hit:attackBox(state.p1)},p2:{hurt:{x:state.p2.x-16,y:state.p2.y-64,width:32,height:64},hit:attackBox(state.p2)}};}
function attackBox(f:FighterState){if(!f.action)return null;const move=f.action===1?MOVES.JAB:MOVES.KICK;if(f.actionFrame<move.startup||f.actionFrame>=move.startup+move.active)return null;return{x:f.facing>0?f.x:f.x-move.reach,y:f.y-(f.action===1?50:35),width:move.reach,height:18};}
export function cloneKombatState(s:KombatState):KombatState{return{frame:s.frame,roundTicks:s.roundTicks,winner:s.winner,p1:{...s.p1},p2:{...s.p2}};}export function kombatChecksum(s:KombatState){let hash=2166136261;for(const value of[s.frame,s.roundTicks,s.winner,...Object.values(s.p1),...Object.values(s.p2)]){hash^=Math.floor(value);hash=Math.imul(hash,16777619);}return hash>>>0;}export const KOMBAT_ADAPTER:DeterministicAdapter<KombatState>={clone:cloneKombatState,step:stepKombat,checksum:kombatChecksum};export function kombatInput(frame:number,buttons:number,axisX:number):NetInputFrame{return{frame,buttons,axisX,axisY:0,checksum:inputChecksum(frame,buttons,axisX,0)};}function fighter(x:number,facing:number):FighterState{return{x,y:408,facing,health:1000,action:0,actionFrame:0,hitstun:0,blockstun:0,combo:0,comboDamage:0};}function clamp(v:number,min:number,max:number){return Math.max(min,Math.min(max,v));}
