import Phaser from 'phaser';
import { AudioEngine } from '../../engine/AudioEngine';
import { createCloth } from '../../engine/physics/SoftBodySolver';
import { voronoiShatter, type Fragment } from '../../engine/physics/VoronoiShatter';
import { InputManager } from '../../engine/InputManager';
import { solveFabrik, type Joint } from '../../graphics/kinematics/Kinematics';
import { inputChecksum, type NetInputFrame } from '../../net/InputCodec';
import { RollbackEngine } from '../../net/rollback/RollbackEngine';
import { initialKombatState, KOMBAT_ADAPTER, kombatInput, type FighterState } from './KombatSystems';
export default class NeonKombatScene extends Phaser.Scene {
  private rollback = new RollbackEngine(initialKombatState(), KOMBAT_ADAPTER); private gfx!: Phaser.GameObjects.Graphics; private hud!: Phaser.GameObjects.Text; private accumulator = 0; private frame = 0; private cape = createCloth(6, 8, 7); private fragments: Fragment[] = [];
  constructor() { super('KombatScene'); }
  create() { this.rollback = new RollbackEngine(initialKombatState(), KOMBAT_ADAPTER); this.accumulator = 0; this.frame = 0; this.cape = createCloth(6, 8, 7); this.fragments = []; this.gfx = this.add.graphics(); this.hud = this.add.text(10, 8, '', { fontFamily: 'Courier', fontSize: '13px', color: '#fff' }).setDepth(5); this.add.text(320, 18, 'NEON KOMBAT // ROLLBACK ARENA', { fontFamily: 'Courier', fontSize: '18px', color: '#ffcc00', fontStyle: 'bold' }).setOrigin(.5).setDepth(5); this.input.keyboard?.on('keydown-ESC', () => this.scene.start('LobbyScene')); AudioEngine.playTrack('kombat'); }
  update(_time: number, delta: number) { this.accumulator += Math.min(50, delta); while (this.accumulator >= 1000 / 60) { this.accumulator -= 1000 / 60; this.step(); } this.cape.step(Math.min(.05, delta / 1000), 280, 3); this.draw(); }
  simulateDesync(frames = 180, delay = 8) { const reference = new RollbackEngine(initialKombatState(), KOMBAT_ADAPTER), late = new RollbackEngine(initialKombatState(), KOMBAT_ADAPTER), queue: NetInputFrame[] = []; for (let frame = 1; frame <= Math.max(1, Math.min(600, frames)); frame++) { const local = kombatInput(frame, frame % 47 === 0 ? 16 : 0, frame % 80 < 40 ? 127 : -127), remote = kombatInput(frame, frame % 53 === 0 ? 16 : 0, frame % 90 < 45 ? -127 : 127); reference.receiveRemote(remote); reference.advance(local); late.advance(local); queue.push(remote); if (queue.length > delay) late.receiveRemote(queue.shift()!); } for (const input of queue) late.receiveRemote(input); return { reference: reference.snapshot().checksum, late: late.snapshot().checksum, metrics: late.snapshot().metrics }; }
  private step() { const frame = ++this.frame, p1 = this.read(frame, 1), p2 = this.read(frame, 2); this.rollback.receiveRemote(p2); const snapshot = this.rollback.advance(p1); if (snapshot.state.p1.health < 700 && this.fragments.length === 0) this.fragments = voronoiShatter(640, 70, { x: snapshot.state.p1.x, y: 35 }, 18, 77); }
  private read(frame: number, player: 1 | 2) { const down = (action: 'UP' | 'LEFT' | 'RIGHT' | 'FIRE') => player === 1 ? InputManager.isP1Down(action) : InputManager.isP2Down(action), buttons = (down('FIRE') ? 16 : 0) | (down('UP') ? 1 : 0), axisX = down('LEFT') ? -127 : down('RIGHT') ? 127 : 0; return { frame, buttons, axisX, axisY: 0, checksum: inputChecksum(frame, buttons, axisX, 0) }; }
  private draw() { const snapshot = this.rollback.snapshot(), state = snapshot.state; this.gfx.clear().fillStyle(0x070313).fillRect(0, 0, 640, 480).fillStyle(0x221144).fillRect(0, 408, 640, 72); for (const fragment of this.fragments) { this.gfx.fillStyle(0x552266, .5); if (fragment.vertices.length >= 3) this.gfx.fillPoints(fragment.vertices, true); } this.drawFighter(state.p1, 0x00ffcc); this.drawFighter(state.p2, 0xff2e88); this.gfx.fillStyle(0x111111).fillRect(40, 42, 240, 12).fillRect(360, 42, 240, 12).fillStyle(0x00ffcc).fillRect(40, 42, 240 * state.p1.health / 1000, 12).fillStyle(0xff2e88).fillRect(600 - 240 * state.p2.health / 1000, 42, 240 * state.p2.health / 1000, 12); for (let i = 0; i < this.cape.x.length; i++) { const row = Math.floor(i / 6); this.gfx.fillStyle(0xffcc00, .25).fillCircle(state.p1.x - 24 + this.cape.x[i] * .35, state.p1.y - 65 + row * 2 + this.cape.y[i] * .25, 2); } this.hud.setText(`FRAME ${state.frame}  TIME ${Math.ceil(state.roundTicks / 60)}  CHECK ${snapshot.checksum.toString(16).padStart(8, '0')}  ROLLBACK ${snapshot.metrics.rollbacks}\nP1 COMBO ${state.p2.combo} / ${state.p2.comboDamage}  P2 COMBO ${state.p1.combo} / ${state.p1.comboDamage}`); }
  private drawFighter(f: FighterState, color: number) { this.gfx.fillStyle(color).fillCircle(f.x, f.y - 58, 10).fillRect(f.x - 10, f.y - 48, 20, 34); const pose = f.action ? f.facing * 28 : 0; for (const side of [-1, 1]) { const shoulder = { x: f.x + side * 8, y: f.y - 43 }, target = { x: f.x + side * 16 + pose, y: f.y - 25 + (f.hitstun ? 8 : 0) }, joints: Joint[] = [shoulder, { x: shoulder.x + side * 10, y: shoulder.y + 12 }, target], arm = solveFabrik(joints, [16, 16], target, 3); this.gfx.lineStyle(5, color).beginPath().moveTo(arm[0].x, arm[0].y).lineTo(arm[1].x, arm[1].y).lineTo(arm[2].x, arm[2].y).strokePath(); } this.gfx.lineStyle(6, color).lineBetween(f.x - 6, f.y - 14, f.x - 13, f.y).lineBetween(f.x + 6, f.y - 14, f.x + 13, f.y); }
}
