import { LamportStateSigner, stateAttestationBytes, verifyLamportState } from '../../engine/crypto/LamportStateSignature';
import { stepRelativisticCombat } from '../../engine/physics/relativistic';
import { proceduralTexture, upscaleNeuralTexture } from '../../graphics/neural/NeuralTexture';
import { renderPathFrame, singularityPathScene } from '../../graphics/pathtracing/PathTracer';
import { generateLensingField } from '../../graphics/pathtracing/HorizonLensing';
import { SpatialShardMesh } from '../../net/sharding/SpatialShardMesh';

export const HORIZON_ARCHITECTURES = ['ARCADE', 'MULTIPLAYER', 'PROCEDURAL', 'TRACKER_AUDIO', 'REPLAY', 'VOXELS', 'PORTALS', 'QUANTUM', 'GENETICS', 'SOCIETY', 'WEBXR', 'WEB_CODECS', 'NEON_OS', 'NEURAL_TERRAIN', 'PATH_TRACING', 'QUORUM_LEDGER', 'HASH_SIGNATURES', 'SPATIAL_SHARDS'] as const;
export function horizonCore(seed = 149) { const source = proceduralTexture(seed, 16, 16), texture = upscaleNeuralTexture(source, 4, seed ^ 17), scene = singularityPathScene(seed); scene.detailTexture = texture; const frame = renderPathFrame(scene, 28, 16, 1, 0), lensing = generateLensingField(128, 72), mesh = new SpatialShardMesh(16); ['alpha', 'beta', 'gamma', 'delta'].forEach(id => mesh.upsertPeer({ id, capacity: 1 })); let state = { x: 320, y: 0, vx: 800, vy: 40, coordinateTime: 0, properTime: 0, frequencyShift: 1 }; for (let index = 0; index < 600; index++) state = stepRelativisticCombat(state, { thrust: .4, turn: Math.sin(index * .03) }, 1 / 60, { x: 0, y: 0, mass: 320_000 }); return { texture, frame, lensing, state, shard: mesh.assign({ x: seed, y: 0, z: -seed }, 2), shardDigest: mesh.convergenceDigest(10_000), architectures: HORIZON_ARCHITECTURES.length }; }
export async function horizonCryptoDiagnostics(seed = 149) { const core = horizonCore(seed), signer = await LamportStateSigner.create(), identity = signer.identity(), message = stateAttestationBytes(core.frame.checksum.toString(16).padStart(64, '0'), 1), proof = await signer.sign(message); return { textureChecksum: core.texture.checksum, frameChecksum: core.frame.checksum, lensingChecksum: core.lensing.checksum, shardDigest: core.shardDigest, owners: core.shard.owners, architectures: core.architectures, speed: Math.hypot(core.state.vx, core.state.vy), properTime: core.state.properTime, coordinateTime: core.state.coordinateTime, doppler: core.state.frequencyShift, signatureValid: await verifyLamportState(message, identity, proof), publicKeyBytes: identity.publicKey.byteLength, signatureBytes: proof.signature.byteLength }; }
