import { proceduralImpulse, spatialSample } from './SpatialDsp';
export interface SpatialEmitterSpec { id: string; x: number; y: number; frequency: number; }
interface LiveEmitter extends SpatialEmitterSpec { oscillator: OscillatorNode; panner: PannerNode; filter: BiquadFilterNode; gain: GainNode; wet: GainNode; }
export class SpatialAudioField {
  private context?: AudioContext; private output?: GainNode; private convolver?: ConvolverNode; private readonly emitters = new Map<string, LiveEmitter>();
  initialize(specs: SpatialEmitterSpec[]) { if (this.context) return; const AudioContextClass = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioContextClass) return; const context = new AudioContextClass(); const output = context.createGain(); output.gain.value = 0.18; output.connect(context.destination); const convolver = context.createConvolver(); const impulse = context.createBuffer(2, Math.floor(context.sampleRate * 0.7), context.sampleRate); const data = proceduralImpulse(context.sampleRate); impulse.copyToChannel(data, 0); impulse.copyToChannel(data, 1); convolver.buffer = impulse; convolver.connect(output); this.context = context; this.output = output; this.convolver = convolver; for (const spec of specs.slice(0, 16)) this.add(spec); }
  update(listenerX: number, listenerY: number, heading: number) { if (!this.context) return; for (const emitter of this.emitters.values()) { const sample = spatialSample(listenerX, listenerY, heading, emitter.x, emitter.y); const now = this.context.currentTime; emitter.panner.positionX.setTargetAtTime(emitter.x - listenerX, now, 0.03); emitter.panner.positionZ.setTargetAtTime(emitter.y - listenerY, now, 0.03); emitter.gain.gain.setTargetAtTime(sample.gain, now, 0.04); emitter.filter.frequency.setTargetAtTime(sample.cutoffHz, now, 0.04); emitter.wet.gain.setTargetAtTime(sample.reverb, now, 0.08); } }
  destroy() { for (const emitter of this.emitters.values()) { emitter.oscillator.stop(); emitter.oscillator.disconnect(); emitter.panner.disconnect(); emitter.filter.disconnect(); emitter.gain.disconnect(); emitter.wet.disconnect(); } this.emitters.clear(); void this.context?.close(); this.context = undefined; }
  private add(spec: SpatialEmitterSpec) { if (!this.context || !this.output || !this.convolver || !/^[a-z0-9-]{1,32}$/.test(spec.id)) return; const oscillator = this.context.createOscillator(); oscillator.type = 'square'; oscillator.frequency.value = Math.max(40, Math.min(1800, spec.frequency)); const panner = this.context.createPanner(); panner.panningModel = 'HRTF'; panner.distanceModel = 'inverse'; panner.refDistance = 1; panner.maxDistance = 20; const filter = this.context.createBiquadFilter(); filter.type = 'lowpass'; const gain = this.context.createGain(); const wet = this.context.createGain(); oscillator.connect(panner); panner.connect(filter); filter.connect(gain); gain.connect(this.output); filter.connect(wet); wet.connect(this.convolver); oscillator.start(); this.emitters.set(spec.id, { ...spec, oscillator, panner, filter, gain, wet }); }
}
