export interface NeuralTexture { width: number; height: number; pixels: Uint8Array<ArrayBuffer>; checksum: number; }

export function proceduralTexture(seed: number, width = 64, height = 64): NeuralTexture { const w = bound(width, 4, 256), h = bound(height, 4, 256), pixels = new Uint8Array(w * h * 4); for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) { const index = (y * w + x) * 4, noise = mix(seed ^ Math.imul(x, 73856093) ^ Math.imul(y, 19349663)), ring = Math.sin(Math.hypot(x - w / 2, y - h / 2) * .45 + seed) * 32; pixels[index] = clampByte(80 + (noise & 63) + ring); pixels[index + 1] = clampByte(35 + (noise >>> 8 & 95) + ring * .4); pixels[index + 2] = clampByte(110 + (noise >>> 16 & 95) - ring * .3); pixels[index + 3] = 255; } return { width: w, height: h, pixels, checksum: checksum(pixels) }; }

export function upscaleNeuralTexture(source: NeuralTexture, scale = 4, seed = 1, pooledOutput?: Uint8Array<ArrayBuffer>): NeuralTexture { validate(source); const factor = scale === 2 ? 2 : scale === 4 ? 4 : 0; if (!factor) throw new Error('Neural texture scale must be 2 or 4'); const width = source.width * factor, height = source.height * factor; if (width > 1024 || height > 1024) throw new Error('Neural texture output exceeds 1,024 pixels per axis'); const output = pooledOutput ?? new Uint8Array(width * height * 4); if (output.length !== width * height * 4) throw new Error('Neural texture pool has the wrong size'); for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) { const sx = x / factor, sy = y / factor, x0 = Math.floor(sx), y0 = Math.floor(sy), fx = sx - x0, fy = sy - y0, phase = (mix(seed ^ x ^ Math.imul(y, 0x9e3779b9)) & 255) - 128; for (let channel = 0; channel < 3; channel++) { const center = sample(source, x0, y0, channel), right = sample(source, x0 + 1, y0, channel), down = sample(source, x0, y0 + 1, channel), diagonal = sample(source, x0 + 1, y0 + 1, channel), base = center * (1 - fx) * (1 - fy) + right * fx * (1 - fy) + down * (1 - fx) * fy + diagonal * fx * fy, gx = right - center, gy = down - center, laplace = right + down - center * 2, hidden0 = Math.max(0, gx * 3 - gy * 2 + phase / 8), hidden1 = Math.max(0, laplace * 2 + gx + gy - phase / 12), detail = (hidden0 - hidden1) / 16; output[(y * width + x) * 4 + channel] = clampByte(base + detail); } output[(y * width + x) * 4 + 3] = 255; } return { width, height, pixels: output, checksum: checksum(output) }; }

export function sampleNeuralTexture(texture: NeuralTexture, x: number, y: number): { x: number; y: number; z: number } { validate(texture); const px = ((Math.floor(Math.abs(x * texture.width)) % texture.width) + texture.width) % texture.width, py = ((Math.floor(Math.abs(y * texture.height)) % texture.height) + texture.height) % texture.height, index = (py * texture.width + px) * 4; return { x: .55 + (texture.pixels[index] as number) / 510, y: .55 + (texture.pixels[index + 1] as number) / 510, z: .55 + (texture.pixels[index + 2] as number) / 510 }; }

export const NEURAL_TEXTURE_WGSL = `
struct Params { sourceWidth: u32, sourceHeight: u32, outputWidth: u32, outputHeight: u32, scale: u32, seed: u32 }
@group(0) @binding(0) var<storage, read> source: array<u32>; @group(0) @binding(1) var<storage, read_write> output: array<u32>; @group(0) @binding(2) var<uniform> params: Params;
fn channel(pixel: u32, shift: u32) -> f32 { return f32((pixel >> shift) & 255u); } fn clampCoord(value: i32, limit: u32) -> u32 { return u32(clamp(value, 0, i32(limit) - 1)); } fn load(x: i32, y: i32) -> u32 { return source[clampCoord(y, params.sourceHeight) * params.sourceWidth + clampCoord(x, params.sourceWidth)]; }
@compute @workgroup_size(8, 8) fn main(@builtin(global_invocation_id) id: vec3u) { if (id.x >= params.outputWidth || id.y >= params.outputHeight) { return; } let sx = f32(id.x) / f32(params.scale); let sy = f32(id.y) / f32(params.scale); let x0 = i32(floor(sx)); let y0 = i32(floor(sy)); let fraction = fract(vec2f(sx, sy)); let a = load(x0, y0); let b = load(x0 + 1, y0); let c = load(x0, y0 + 1); let d = load(x0 + 1, y0 + 1); var packed = 255u << 24u; for (var shift = 0u; shift <= 16u; shift += 8u) { let center = channel(a, shift); let right = channel(b, shift); let down = channel(c, shift); let base = mix(mix(center, right, fraction.x), mix(down, channel(d, shift), fraction.x), fraction.y); let gx = right - center; let gy = down - center; let hidden = max(0.0, gx * 3.0 - gy * 2.0) - max(0.0, (right + down - center * 2.0) * 2.0 + gx + gy); packed |= u32(clamp(base + hidden / 16.0, 0.0, 255.0)) << shift; } output[id.y * params.outputWidth + id.x] = packed; }`;
interface Device { createShaderModule(input: { code: string }): unknown; createComputePipelineAsync(input: unknown): Promise<unknown>; }
export async function compileNeuralTexturePipeline(): Promise<'COMPILED' | 'UNAVAILABLE'> { if (typeof navigator === 'undefined') return 'UNAVAILABLE'; const gpu = (navigator as Navigator & { gpu?: { requestAdapter(): Promise<{ requestDevice(): Promise<Device> } | null> } }).gpu; if (!gpu) return 'UNAVAILABLE'; const adapter = await gpu.requestAdapter(); if (!adapter) return 'UNAVAILABLE'; const device = await adapter.requestDevice(); const module = device.createShaderModule({ code: NEURAL_TEXTURE_WGSL }); await device.createComputePipelineAsync({ layout: 'auto', compute: { module, entryPoint: 'main' } }); return 'COMPILED'; }
function sample(source: NeuralTexture, x: number, y: number, channel: number) { const px = Math.max(0, Math.min(source.width - 1, x)), py = Math.max(0, Math.min(source.height - 1, y)); return source.pixels[(py * source.width + px) * 4 + channel] as number; } function validate(texture: NeuralTexture) { if (!texture || !Number.isInteger(texture.width) || !Number.isInteger(texture.height) || texture.width < 1 || texture.height < 1 || texture.width > 1024 || texture.height > 1024 || texture.pixels.length !== texture.width * texture.height * 4) throw new Error('Invalid neural texture'); }
function bound(value: number, low: number, high: number) { return Math.max(low, Math.min(high, Math.floor(value))); } function clampByte(value: number) { return Math.max(0, Math.min(255, Math.round(value))); } function mix(value: number) { value ^= value >>> 16; value = Math.imul(value, 0x7feb352d); value ^= value >>> 15; value = Math.imul(value, 0x846ca68b); return (value ^ value >>> 16) >>> 0; } function checksum(bytes: Uint8Array) { let value = 2166136261; for (const byte of bytes) value = Math.imul(value ^ byte, 16777619); return value >>> 0; }
