import { inputChecksum, type NetInputFrame } from '../InputCodec';
import { StateHistoryRing } from './StateHistoryRing';
export interface DeterministicAdapter<State> { clone(state: State): State; step(state: State, local: NetInputFrame, remote: NetInputFrame): State; checksum(state: State): number; }
export interface RollbackMetrics { rollbacks: number; resimulatedFrames: number; maxResimulation: number; lastResimulationMs: number; }
export class RollbackEngine<State> {
  private readonly history: StateHistoryRing<State>; private readonly local = new Map<number, NetInputFrame>(); private readonly remote = new Map<number, NetInputFrame>(); private readonly usedRemote = new Map<number, NetInputFrame>(); private state: State; private frame = 0; private metrics: RollbackMetrics = { rollbacks: 0, resimulatedFrames: 0, maxResimulation: 0, lastResimulationMs: 0 }; private readonly adapter:DeterministicAdapter<State>; readonly historyFrames:number;
  constructor(initial: State, adapter: DeterministicAdapter<State>, historyFrames = 240) { this.adapter=adapter;this.historyFrames=historyFrames;if (historyFrames < 8 || historyFrames > 600) throw new Error('Rollback history must contain 8 to 600 frames'); this.state = adapter.clone(initial); this.history = new StateHistoryRing(historyFrames + 1, adapter.clone); this.history.set(0, initial); }
  advance(local: NetInputFrame) { if (!valid(local) || local.frame !== this.frame + 1) throw new Error('Local rollback input must be valid and sequential'); this.local.set(local.frame, local); const predicted = this.remote.get(local.frame) ?? this.lastRemote(local.frame); this.usedRemote.set(local.frame, predicted); this.state = this.adapter.step(this.state, local, predicted); this.frame = local.frame; this.history.set(this.frame, this.state); this.prune(); return this.snapshot(); }
  receiveRemote(input: NetInputFrame) { if (!valid(input)) throw new Error('Remote rollback input checksum mismatch'); if (input.frame < Math.max(1, this.frame - this.historyFrames) || input.frame > this.frame + this.historyFrames) return false; this.remote.set(input.frame, input); const used = this.usedRemote.get(input.frame); if (input.frame > this.frame || !used || same(used, input)) return false; const before = this.history.get(input.frame - 1); if (!before) return false; const started = performance.now(); this.state = before; let count = 0; for (let frame = input.frame; frame <= this.frame; frame++) { const local = this.local.get(frame); if (!local) break; const remote = this.remote.get(frame) ?? this.lastRemote(frame); this.usedRemote.set(frame, remote); this.state = this.adapter.step(this.state, local, remote); this.history.set(frame, this.state); count++; } this.metrics = { rollbacks: this.metrics.rollbacks + 1, resimulatedFrames: this.metrics.resimulatedFrames + count, maxResimulation: Math.max(this.metrics.maxResimulation, count), lastResimulationMs: performance.now() - started }; return true; }
  snapshot() { return { frame: this.frame, state: this.adapter.clone(this.state), checksum: this.adapter.checksum(this.state), metrics: { ...this.metrics } }; }
  private lastRemote(frame: number) { for (let candidate = frame - 1; candidate >= Math.max(0, frame - this.historyFrames); candidate--) { const input = this.remote.get(candidate); if (input) return { ...input, frame, checksum: inputChecksum(frame, input.buttons, input.axisX, input.axisY) }; } return neutral(frame); }
  private prune() { const cutoff = this.frame - this.historyFrames; for (const map of [this.local, this.remote, this.usedRemote]) for (const key of map.keys()) if (key < cutoff) map.delete(key); }
}
function neutral(frame: number): NetInputFrame { return { frame, buttons: 0, axisX: 0, axisY: 0, checksum: inputChecksum(frame, 0, 0, 0) }; }
function valid(input: NetInputFrame) { return Number.isInteger(input.frame) && input.frame >= 0 && input.checksum === inputChecksum(input.frame, input.buttons, input.axisX, input.axisY); }
function same(a: NetInputFrame, b: NetInputFrame) { return a.buttons === b.buttons && a.axisX === b.axisX && a.axisY === b.axisY; }
