export interface QuantumBranch { value: number[]; real: number; imaginary: number; }
export interface QuantumObject { id: string; position: { x: number; y: number; z: number }; branches: QuantumBranch[]; collapsed?: number; entanglement?: string; }
export interface QuantumObservation { id: string; branch: number; probability: number; entangled: string[]; }

export class QuantumStateSolver {
  private readonly objects = new Map<string, QuantumObject>(); private observation = 0; private readonly seed: number;
  constructor(seed = 0x5155414e) { this.seed = seed; }
  add(object: QuantumObject) { validateObject(object); if (this.objects.size >= 4096 || this.objects.has(object.id)) throw new Error('Quantum object capacity or identity conflict'); const copy = clone(object); normalize(copy.branches); this.objects.set(copy.id, copy); return clone(copy); }
  entangle(group: string, ids: readonly string[]) { if (!/^[a-z0-9:-]{1,48}$/.test(group) || ids.length < 2 || ids.length > 16) throw new Error('Invalid entanglement group'); const objects = ids.map(id => this.require(id)), width = objects[0].branches.length; if (objects.some(object => object.branches.length !== width)) throw new Error('Entangled objects require matching branch counts'); for (const object of objects) object.entanglement = group; }
  evolve(deltaSeconds: number) { const dt = clamp(deltaSeconds, 0, .1); for (const object of this.objects.values()) if (object.collapsed === undefined) for (let index = 0; index < object.branches.length; index++) { const branch = object.branches[index], phase = dt * (index + 1) * .7, cosine = Math.cos(phase), sine = Math.sin(phase), real = branch.real * cosine - branch.imaginary * sine; branch.imaginary = branch.real * sine + branch.imaginary * cosine; branch.real = real; } }
  observe(id: string, camera: { x: number; y: number; z: number }, range = 32): QuantumObservation | undefined { const object = this.require(id); if (distance(object.position, camera) > clamp(range, .1, 4096)) return undefined; if (object.collapsed !== undefined) return { id, branch: object.collapsed, probability: 1, entangled: [] }; const probabilities = object.branches.map(branch => branch.real * branch.real + branch.imaginary * branch.imaginary), branch = select(probabilities, random01(this.seed, hash(id), this.observation++)), group = object.entanglement, linked = group ? [...this.objects.values()].filter(item => item.entanglement === group) : [object]; for (const item of linked) item.collapsed = branch; return { id, branch, probability: probabilities[branch], entangled: linked.filter(item => item.id !== id).map(item => item.id).sort() }; }
  reset(id: string) { const object = this.require(id); object.collapsed = undefined; normalize(object.branches); }
  get(id: string) { return clone(this.require(id)); }
  probabilities(id: string) { const object = this.require(id); if (object.collapsed !== undefined) return object.branches.map((_, index) => Number(index === object.collapsed)); return object.branches.map(branch => branch.real * branch.real + branch.imaginary * branch.imaginary); }
  private require(id: string) { const object = this.objects.get(id); if (!object) throw new Error('Unknown quantum object'); return object; }
}

export function equalSuperposition(id: string, branches: number, position = { x: 0, y: 0, z: 0 }): QuantumObject { const count = Math.max(2, Math.min(16, Math.floor(branches))), amplitude = 1 / Math.sqrt(count); return { id, position: { ...position }, branches: Array.from({ length: count }, (_, index) => ({ value: [index], real: amplitude, imaginary: 0 })) }; }
function validateObject(object: QuantumObject) { if (!/^[a-z0-9:-]{1,48}$/.test(object.id) || object.branches.length < 2 || object.branches.length > 16 || object.branches.some(branch => branch.value.length > 8 || branch.value.some(value => !Number.isFinite(value)) || !Number.isFinite(branch.real) || !Number.isFinite(branch.imaginary)) || Object.values(object.position).some(value => !Number.isFinite(value))) throw new Error('Invalid quantum object'); }
function normalize(branches: QuantumBranch[]) { const length = Math.sqrt(branches.reduce((sum, branch) => sum + branch.real ** 2 + branch.imaginary ** 2, 0)); if (!length) throw new Error('Quantum amplitudes cannot all be zero'); for (const branch of branches) { branch.real /= length; branch.imaginary /= length; } }
function select(weights: number[], target: number) { let cursor = target * weights.reduce((sum, weight) => sum + weight, 0); for (let index = 0; index < weights.length; index++) { cursor -= weights[index]; if (cursor <= 0) return index; } return weights.length - 1; }
function random01(seed: number, value: number, counter: number) { let state = seed ^ value ^ Math.imul(counter + 1, 0x9e3779b9); state ^= state << 13; state ^= state >>> 17; state ^= state << 5; return (state >>> 0) / 4294967296; }
function hash(value: string) { let result = 2166136261; for (let i = 0; i < value.length; i++) result = Math.imul(result ^ value.charCodeAt(i), 16777619); return result >>> 0; }
function distance(a: { x: number; y: number; z: number }, b: { x: number; y: number; z: number }) { return Math.hypot(a.x - b.x, a.y - b.y, a.z - b.z); }
function clone(object: QuantumObject): QuantumObject { return { ...object, position: { ...object.position }, branches: object.branches.map(branch => ({ ...branch, value: [...branch.value] })) }; }
function clamp(value: number, low: number, high: number) { return Math.max(low, Math.min(high, Number.isFinite(value) ? value : low)); }
