import Phaser from 'phaser';
import { AudioEngine } from '../../engine/AudioEngine';
import { InputManager } from '../../engine/InputManager';
import { arcadeModRuntime } from '../../mods/ModRuntime';
import type { ArcadeMode } from '../../multiplayer/CoopSession';
import { advanceRacer, collisionSeverity, generateRoadSample, projectRoadScanline, shiftGear } from './RacerSystems';
import { GhostBrain, racerSensors } from '../../ai/neural/GhostBrain';

export default class NeonRacerScene extends Phaser.Scene {
  private road!: Phaser.GameObjects.Graphics; private world!: Phaser.GameObjects.Graphics; private hud!: Phaser.GameObjects.Text; private playerLane = 0; private speed = 0; private gear = 1; private nitro = 100; private distance = 0; private score = 0; private shiftHeld = false; private crashCooldown = 0; private difficulty = 'NORMAL'; private mode: ArcadeMode = 'SOLO'; private ghost!: GhostBrain; private ghostLane = 0; private ghostSpeed = 0; private ghostDistance = 0; private ghostDecisionMs = 0;
  constructor() { super('RacerScene'); }
  create(data: { difficulty?: string; mode?: ArcadeMode }) { this.difficulty = data.difficulty ?? 'NORMAL'; this.mode = data.mode ?? 'SOLO'; this.playerLane = 0; this.speed = 0; this.gear = 1; this.nitro = 100; this.distance = 0; this.score = 0; this.ghostLane = 0; this.ghostSpeed = 0; this.ghostDistance = 0; this.ghostDecisionMs = 0; this.ghost = new GhostBrain('retro_racer_ghost_v1', localStorage); this.road = this.add.graphics(); this.world = this.add.graphics(); this.hud = this.add.text(12, 10, '', { fontFamily: 'Courier', fontSize: '13px', color: '#ffffff' }).setDepth(20); this.add.text(320, 15, 'NEON RETRO RACER // OUTRUN CORE', { fontFamily: 'Courier', fontSize: '18px', color: '#ff2ec4', fontStyle: 'bold' }).setOrigin(0.5).setDepth(20); this.add.text(628, 42, 'STEER A/D  THROTTLE W  BRAKE S  SHIFT SPACE  NITRO SHIFT', { fontFamily: 'Courier', fontSize: '9px', color: '#88aaaa' }).setOrigin(1, 0).setDepth(20); this.input.keyboard?.on('keydown-ESC', () => { this.scene.pause(); this.scene.launch('PauseScene', { scene: this.scene.key }); }); this.events.once('shutdown', () => this.ghost.save()); AudioEngine.playTrack('racer'); }
  update(_time: number, delta: number) { const dt = Math.min(delta, 50) / 1000; const left = InputManager.isP1Down('LEFT'); const right = InputManager.isP1Down('RIGHT'); const throttle = InputManager.isP1Down('UP') ? 1 : 0; const brake = InputManager.isP1Down('DOWN'); const shift = InputManager.isP1Down('FIRE'); if (shift && !this.shiftHeld) { this.gear = shiftGear(this.gear, brake ? -1 : 1); AudioEngine.playEffect('COIN'); } this.shiftHeld = shift; const boosting = InputManager.isDown('ShiftLeft') && this.nitro > 0; this.speed = advanceRacer(this.speed, throttle, brake, this.gear, dt); if (boosting) { this.speed += 85 * dt; this.nitro = Math.max(0, this.nitro - 28 * dt); } else this.nitro = Math.min(100, this.nitro + 4 * dt); this.playerLane = Phaser.Math.Clamp(this.playerLane + (left === right ? 0 : left ? -1 : 1) * dt * (0.8 + this.speed / 260), -1.15, 1.15); this.distance += this.speed * dt; this.score += Math.floor(this.speed * dt * (boosting ? 2 : 1)); this.crashCooldown = Math.max(0, this.crashCooldown - delta); this.updateGhost(delta, dt); this.drawRoad(); this.drawWorld(); this.hud.setText(`SCORE ${this.score}  SPEED ${Math.floor(this.speed)}  GEAR ${this.gear}  NITRO ${Math.floor(this.nitro)}  GHOST ${Math.floor(this.ghostDistance - this.distance)}`); }
  private updateGhost(delta: number, dt: number) { this.ghostDecisionMs -= delta; const sample = generateRoadSample(Math.floor(this.ghostDistance / 30) + 4); if (this.ghostDecisionMs <= 0) { const reward = this.ghostSpeed / 300 - Math.max(0, Math.abs(this.ghostLane) - 1) * 2; const steer = this.ghost.decide(racerSensors(this.ghostLane, sample.curve, this.ghostSpeed, 0, sample.lane * 0.72, 0.8), reward); this.ghostLane = Phaser.Math.Clamp(this.ghostLane + steer * 0.09, -1.15, 1.15); this.ghostDecisionMs = 80; } this.ghostSpeed = advanceRacer(this.ghostSpeed, 1, false, Math.min(5, 1 + Math.floor(this.ghostSpeed / 65)), dt); this.ghostDistance += this.ghostSpeed * dt; }
  private drawRoad() { const horizon = 132; const segment = Math.floor(this.distance / 20); const curve = generateRoadSample(segment).curve; this.road.clear().fillStyle(0x120022).fillRect(0, 0, 640, horizon).fillStyle(0xff4d88).fillCircle(500, 72, 34).fillStyle(0x050817).fillRect(0, horizon, 640, 348); for (let y = horizon; y < 480; y += 4) { const projected = projectRoadScanline(y, horizon, 640, curve); const stripe = (Math.floor(this.distance / 8) + Math.floor((1 - projected.scale) * 24)) % 2 === 0; this.road.fillStyle(stripe ? 0x20243a : 0x171b2e).fillRect(projected.center - projected.halfWidth, y, projected.halfWidth * 2, 4); this.road.fillStyle(0xff2ec4).fillRect(projected.center - projected.halfWidth, y, Math.max(1, projected.scale * 6), 4).fillRect(projected.center + projected.halfWidth - Math.max(1, projected.scale * 6), y, Math.max(1, projected.scale * 6), 4); if (stripe) this.road.fillStyle(0xffffcc).fillRect(projected.center - 2, y, 4, Math.max(1, projected.scale * 4)); } }
  private drawWorld() { this.world.clear(); const base = Math.floor(this.distance / 30); const patches = arcadeModRuntime.stagePatches(); const objects = Array.from({ length: 18 }, (_, index) => { const sample = generateRoadSample(base + index); const depth = 1 - index / 19; return { ...sample, depth, lane: sample.lane * 0.72 }; }); for (const patch of patches) for (const hazard of patch.hazards.slice(0, 12)) objects.push({ ...generateRoadSample(base + hazard.lane * 7), depth: 1 - hazard.offset * 0.8, lane: (hazard.lane / 7) * 2 - 1 }); objects.sort((a, b) => a.depth - b.depth); for (const object of objects) { const scale = object.depth * object.depth; const y = 132 + scale * 330; const center = projectRoadScanline(y, 132, 640, generateRoadSample(base).curve).center; const x = center + object.lane * scale * 250; const size = 4 + scale * 34; this.world.fillStyle(object.roadside === 'TREE' ? 0x00ff88 : object.roadside === 'SIGN' ? 0xffff00 : 0x00ccff).fillRect(x - size / 2, y - size, size, size); const severity = collisionSeverity(this.playerLane, object.lane, object.depth); if (severity > 0 && this.crashCooldown === 0) { this.speed *= 0.42; this.crashCooldown = 800; this.cameras.main.shake(180, 0.012); AudioEngine.playEffect('EXPLOSION'); } } const ghostX = 320 + this.ghostLane * 135; this.world.fillStyle(0x00aaff, 0.58).fillTriangle(ghostX, 410, ghostX - 18, 434, ghostX + 18, 434); const playerX = 320 + this.playerLane * 150; this.world.fillStyle(this.crashCooldown > 0 ? 0xffffff : 0xff2ec4, 1).fillTriangle(playerX, 445, playerX - 24, 475, playerX + 24, 475).fillStyle(0x00ffff).fillRect(playerX - 16, 456, 32, 8); if (this.distance >= 10000 || this.ghostDistance >= 10000) this.finish(); }
  private finish() { this.scene.pause(); this.ghost.save(); const key = `${this.difficulty}-${this.mode}`; const winner = this.distance >= this.ghostDistance ? 'HUMAN WINS' : 'GHOST WINS'; this.scene.launch('GameOverScene', { scene: this.scene.key, title: `FINISH LINE\n${winner}`, score: this.score, difficulty: key, restartData: { difficulty: this.difficulty, mode: this.mode }, submitScore: true, color: '#00ffcc' }); }
}
