export interface NetworkSnapshot { version: 1; inputs: number; hidden: number; outputs: number; weightsInput: number[]; weightsOutput: number[]; biasHidden: number[]; biasOutput: number[]; }

export class DenseQNetwork {
  private readonly weightsInput: Float32Array; private readonly weightsOutput: Float32Array; private readonly biasHidden: Float32Array; private readonly biasOutput: Float32Array;
  readonly inputs: number; readonly hidden: number; readonly outputs: number;
  constructor(inputs: number, hidden: number, outputs: number, random: () => number = Math.random) { if (inputs < 1 || inputs > 64 || hidden < 1 || hidden > 128 || outputs < 1 || outputs > 32) throw new Error('Network dimensions are outside engine bounds'); this.inputs = inputs; this.hidden = hidden; this.outputs = outputs; this.weightsInput = seededArray(inputs * hidden, random, inputs); this.weightsOutput = seededArray(hidden * outputs, random, hidden); this.biasHidden = new Float32Array(hidden); this.biasOutput = new Float32Array(outputs); }
  forward(input: readonly number[]) { if (input.length !== this.inputs) throw new Error('Neural input length mismatch'); const hiddenValues = new Float32Array(this.hidden); for (let h = 0; h < this.hidden; h++) { let sum = this.biasHidden[h]; for (let i = 0; i < this.inputs; i++) sum += finite(input[i]) * this.weightsInput[h * this.inputs + i]; hiddenValues[h] = Math.tanh(sum); } const output = new Float32Array(this.outputs); for (let o = 0; o < this.outputs; o++) { let sum = this.biasOutput[o]; for (let h = 0; h < this.hidden; h++) sum += hiddenValues[h] * this.weightsOutput[o * this.hidden + h]; output[o] = sum; } return { hidden: hiddenValues, output }; }
  train(input: readonly number[], target: readonly number[], learningRate = 0.01) { if (target.length !== this.outputs) throw new Error('Neural target length mismatch'); const rate = clamp(learningRate, 0.00001, 0.2); const activation = this.forward(input); const outputDelta = new Float32Array(this.outputs); for (let o = 0; o < this.outputs; o++) outputDelta[o] = clamp(finite(target[o]) - activation.output[o], -4, 4); const hiddenDelta = new Float32Array(this.hidden); for (let h = 0; h < this.hidden; h++) { let error = 0; for (let o = 0; o < this.outputs; o++) error += outputDelta[o] * this.weightsOutput[o * this.hidden + h]; hiddenDelta[h] = error * (1 - activation.hidden[h] * activation.hidden[h]); } for (let o = 0; o < this.outputs; o++) { for (let h = 0; h < this.hidden; h++) this.weightsOutput[o * this.hidden + h] += rate * outputDelta[o] * activation.hidden[h]; this.biasOutput[o] += rate * outputDelta[o]; } for (let h = 0; h < this.hidden; h++) { for (let i = 0; i < this.inputs; i++) this.weightsInput[h * this.inputs + i] += rate * hiddenDelta[h] * finite(input[i]); this.biasHidden[h] += rate * hiddenDelta[h]; } return outputDelta.reduce((sum, value) => sum + value * value, 0) / this.outputs; }
  snapshot(): NetworkSnapshot { return { version: 1, inputs: this.inputs, hidden: this.hidden, outputs: this.outputs, weightsInput: [...this.weightsInput], weightsOutput: [...this.weightsOutput], biasHidden: [...this.biasHidden], biasOutput: [...this.biasOutput] }; }
  restore(snapshot: NetworkSnapshot) { if (snapshot.version !== 1 || snapshot.inputs !== this.inputs || snapshot.hidden !== this.hidden || snapshot.outputs !== this.outputs || snapshot.weightsInput.length !== this.weightsInput.length || snapshot.weightsOutput.length !== this.weightsOutput.length || snapshot.biasHidden.length !== this.biasHidden.length || snapshot.biasOutput.length !== this.biasOutput.length) throw new Error('Neural snapshot shape mismatch'); this.weightsInput.set(snapshot.weightsInput.map(finite)); this.weightsOutput.set(snapshot.weightsOutput.map(finite)); this.biasHidden.set(snapshot.biasHidden.map(finite)); this.biasOutput.set(snapshot.biasOutput.map(finite)); }
}

function seededArray(length: number, random: () => number, fanIn: number) { const values = new Float32Array(length); const scale = Math.sqrt(2 / fanIn); for (let index = 0; index < length; index++) values[index] = (random() * 2 - 1) * scale; return values; }
function finite(value: number) { return Number.isFinite(value) ? clamp(value, -1000, 1000) : 0; }
function clamp(value: number, minimum: number, maximum: number) { return Math.max(minimum, Math.min(maximum, value)); }
