export interface LamportPublicIdentity { algorithm: 'LAMPORT-SHA256-OTS'; actor: string; publicKey: Uint8Array<ArrayBuffer>; }
export interface LamportStateProof { algorithm: 'LAMPORT-SHA256-OTS'; actor: string; messageHash: string; signature: Uint8Array<ArrayBuffer>; }

const HASH_BYTES = 32, MESSAGE_BITS = 256, KEY_PARTS = MESSAGE_BITS * 2;

export class LamportStateSigner {
  private readonly secrets: Uint8Array<ArrayBuffer>; private readonly identityValue: LamportPublicIdentity; private consumed = false;
  private constructor(secrets: Uint8Array<ArrayBuffer>, identity: LamportPublicIdentity) { this.secrets = secrets; this.identityValue = identity; }
  static async create(): Promise<LamportStateSigner> { const secrets = new Uint8Array(KEY_PARTS * HASH_BYTES); crypto.getRandomValues(secrets); const publicKey = new Uint8Array(KEY_PARTS * HASH_BYTES); await Promise.all(Array.from({ length: KEY_PARTS }, async (_, index) => publicKey.set(await digest(secrets.slice(index * HASH_BYTES, (index + 1) * HASH_BYTES)), index * HASH_BYTES))); const actor = hex(await digest(publicKey)).slice(0, 32); return new LamportStateSigner(secrets, { algorithm: 'LAMPORT-SHA256-OTS', actor, publicKey }); }
  identity(): LamportPublicIdentity { return { ...this.identityValue, publicKey: this.identityValue.publicKey.slice() }; }
  async sign(message: Uint8Array): Promise<LamportStateProof> { if (this.consumed) throw new Error('Lamport key has already signed one state'); this.consumed = true; const messageDigest = await digest(message), signature = new Uint8Array(MESSAGE_BITS * HASH_BYTES); for (let bit = 0; bit < MESSAGE_BITS; bit++) { const value = (messageDigest[bit >> 3] as number) >> (7 - (bit & 7)) & 1, source = (bit * 2 + value) * HASH_BYTES; signature.set(this.secrets.slice(source, source + HASH_BYTES), bit * HASH_BYTES); } this.secrets.fill(0); return { algorithm: 'LAMPORT-SHA256-OTS', actor: this.identityValue.actor, messageHash: hex(messageDigest), signature }; }
}

export async function verifyLamportState(message: Uint8Array, identity: LamportPublicIdentity, proof: LamportStateProof): Promise<boolean> { if (identity.algorithm !== 'LAMPORT-SHA256-OTS' || proof.algorithm !== identity.algorithm || proof.actor !== identity.actor || identity.publicKey.byteLength !== KEY_PARTS * HASH_BYTES || proof.signature.byteLength !== MESSAGE_BITS * HASH_BYTES) return false; const messageDigest = await digest(message); if (hex(messageDigest) !== proof.messageHash || hex(await digest(identity.publicKey)).slice(0, 32) !== identity.actor) return false; for (let bit = 0; bit < MESSAGE_BITS; bit++) { const value = (messageDigest[bit >> 3] as number) >> (7 - (bit & 7)) & 1, publicOffset = (bit * 2 + value) * HASH_BYTES, signatureOffset = bit * HASH_BYTES, hashed = await digest(proof.signature.slice(signatureOffset, signatureOffset + HASH_BYTES)); if (!equal(hashed, identity.publicKey.subarray(publicOffset, publicOffset + HASH_BYTES))) return false; } return true; }
export function stateAttestationBytes(root: string, length: number): Uint8Array<ArrayBuffer> { if (!/^[a-f0-9]{64}$/.test(root) || !Number.isSafeInteger(length) || length < 0) throw new Error('Invalid state attestation'); return new TextEncoder().encode(`BIOS-STATE-1|${length}|${root}`); }
async function digest(bytes: Uint8Array): Promise<Uint8Array<ArrayBuffer>> { const copy = new Uint8Array(bytes); return new Uint8Array(await crypto.subtle.digest('SHA-256', copy.buffer)); }
function hex(bytes: Uint8Array) { return [...bytes].map(value => value.toString(16).padStart(2, '0')).join(''); }
function equal(a: Uint8Array, b: Uint8Array) { if (a.length !== b.length) return false; let difference = 0; for (let index = 0; index < a.length; index++) difference |= (a[index] as number) ^ (b[index] as number); return difference === 0; }
