import { generateBspDungeon, type Dungeon } from '../games/raycaster/RaycasterSystems';
export interface ArcadeCabinet { id: string; label: string; scene: string; x: number; y: number; frequency: number; }
export interface PresenceState { peerId: string; x: number; y: number; angle: number; frame: number; }
const FLAGSHIPS = [['asteroids','VECTOR ASTEROIDS','AsteroidsScene'],['runner','PIXEL RUNNER','RunnerScene'],['breaker','NEON BREAKER','BreakoutScene'],['invaders','SPACE DEFENDERS','InvadersScene'],['racer','CYBER-RACER','RacerScene'],['caster','CYBER-CASTER','RaycasterScene']] as const;
export function generateArcadeHall(seed = 0x4d455441) { const dungeon = generateBspDungeon(1, 32, 32, seed); const cabinets: ArcadeCabinet[] = FLAGSHIPS.map((entry, index) => { const room = dungeon.rooms[index % dungeon.rooms.length]; return { id: entry[0], label: entry[1], scene: entry[2], x: room.x + 1.5 + index % Math.max(1, room.width - 2), y: room.y + room.height - 1.35, frequency: 110 + index * 37 }; }); return { dungeon, cabinets }; }
export function nearestCabinet(cabinets: ArcadeCabinet[], x: number, y: number, radius = 1.1) { return cabinets.map(cabinet => ({ cabinet, distance: Math.hypot(cabinet.x - x, cabinet.y - y) })).filter(item => item.distance <= radius).sort((a, b) => a.distance - b.distance)[0]?.cabinet; }
export function validatePresence(value: unknown): PresenceState | null { if (!record(value) || typeof value.peerId !== 'string' || !/^[a-z0-9-]{1,32}$/.test(value.peerId) || !finite(value.x, -64, 64) || !finite(value.y, -64, 64) || !finite(value.angle, -100, 100) || !Number.isInteger(value.frame) || Number(value.frame) < 0) return null; return { peerId: value.peerId, x: Number(value.x), y: Number(value.y), angle: Number(value.angle), frame: Number(value.frame) }; }
export class PresenceMesh extends EventTarget { private readonly peers = new Set<{ sendControl(value: unknown): boolean }>(); private readonly states = new Map<string, PresenceState>(); add(peer: { sendControl(value: unknown): boolean }) { if (this.peers.size >= 8) throw new Error('Presence mesh peer limit reached'); this.peers.add(peer); } remove(peer: { sendControl(value: unknown): boolean }) { this.peers.delete(peer); } broadcast(state: PresenceState) { const safe = validatePresence(state); if (!safe) throw new Error('Invalid presence state'); for (const peer of this.peers) peer.sendControl({ type: 'HUB_PRESENCE', state: safe }); } receive(value: unknown) { if (!record(value) || value.type !== 'HUB_PRESENCE') return false; const state = validatePresence(value.state); if (!state) return false; const previous = this.states.get(state.peerId); if (previous && previous.frame >= state.frame) return false; this.states.set(state.peerId, state); this.dispatchEvent(new CustomEvent('presence', { detail: state })); return true; } snapshot() { return [...this.states.values()].map(state => ({ ...state })); } }
export type ArcadeHall = { dungeon: Dungeon; cabinets: ArcadeCabinet[] };
function finite(value: unknown, minimum: number, maximum: number) { return typeof value === 'number' && Number.isFinite(value) && value >= minimum && value <= maximum; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
